New alphabetical chapter sort
tachiyomiorg/tachiyomi pull request #10073
Opened 2023-10-27 11:53 UTC by Opi-Txm

This should close #9997. 
I have only added supporting string values for english and japanese in i18n/src/main/res/values.
I attatched images of the changes below for comparison.

This is my first attempt to contribute to an open source project. If you see any mistakes, please let me know. 
### Images
**Before**
![Before](https://github.com/tachiyomiorg/tachiyomi/assets/106656898/e4598ee2-a88a-4231-b890-18d4bab89b44)
**After**
![After](https://github.com/tachiyomiorg/tachiyomi/assets/106656898/9be5b87e-5994-4259-98c4-90b5b97ff70d)

2023-10-27 18:50 UTC, arkon requested changes

2023-10-27 18:50 UTC, arkon commented on domain/src/main/java/tachiyomi/domain/chapter/service/ChapterSort.kt
> +        Manga.CHAPTER_SORTING_ALPHABET -> when (sortDescending) {
It's a bit more complicated than this to deal with other languages. You can refer to how [the library does it](https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreenModel.kt#L240-L246).

We may want to extract that collator usage out so we can reuse it.

2023-10-27 18:50 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/manga/ChapterSettingsDialog.kt
> +        R.string.sort_by_alphabet to Manga.CHAPTER_SORTING_ALPHABET,
Can reuse `R.string.action_sort_alpha` here. I'll probably reword the other ones separately, they don't necessarily need to be worded like "By xyz".

2023-11-04 14:37 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/manga/model/Manga.kt
>          const val CHAPTER_SORTING_MASK = 0x00000300L
this needs to be changed i think not sure to what

2023-11-04 15:59 UTC, scb261 commented on domain/src/main/java/tachiyomi/domain/manga/model/Manga.kt
>          const val CHAPTER_SORTING_MASK = 0x00000300L
I think it's fine? 3(10)=11(2) which covers the new sorting option. The next one (if ever) will require 7(10)=111(2) mask though

2023-11-04 19:47 UTC, merged