Combining manga information into a function
tachiyomiorg/tachiyomi pull request #10093
Opened 2023-10-31 16:29 UTC by e-shl

2023-10-31 18:30 UTC, AntsyLich requested changes
Also did you make sure the the layouts look the same in both tablet and normal view?

2023-10-31 18:30 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt
> +            isStubSource,
```suggestion
        MangaContentInfo(
            title = title,
            doSearch = doSearch,
            author = author,
            artist = artist,
            status = status,
            sourceName = sourceName,
            isStubSource = isStubSource,
```

2023-10-31 18:30 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt
> +            )
```suggestion
            MangaContentInfo(
                title = title,
                doSearch = doSearch,
                author = author,
                artist = artist,
                status = status,
                sourceName = sourceName,
                isStubSource = isStubSource,
            )
```

2023-10-31 18:30 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt
> +    context: Context,
```suggestion
```

2023-10-31 18:30 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt
> +) {
```suggestion
) {
    val context = LocalContext.current
```

2023-10-31 19:17 UTC, e-shl commented
> Also did you make sure the the layouts look the same in both tablet and normal view?

Old and new code on one screen
![2023-11-01_00-16-35](https://github.com/tachiyomiorg/tachiyomi/assets/35057681/19cebe80-9887-40c4-9733-5ebaab5e244b)
![2023-11-01_00-17-08](https://github.com/tachiyomiorg/tachiyomi/assets/35057681/089271c2-745f-4f31-b936-70a73cfadc0f)

2023-10-31 19:20 UTC, AntsyLich approved these changes

2023-11-01 02:20 UTC, arkon requested changes

2023-11-01 02:20 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt
> -            textAlign = TextAlign.Center,
These center alignments are required for longer text.

2023-11-01 04:45 UTC, e-shl commented on app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt
> -            textAlign = TextAlign.Center,
> These center alignments are required for longer text.
> 
> You could potentially provide different `LocalTextStyle`s to avoid needing to pass it down.

So?
![2023-11-01_09-44-01](https://github.com/tachiyomiorg/tachiyomi/assets/35057681/10168e5b-5c0b-4533-b0ff-e0382d709b99)
![2023-11-01_09-44-11](https://github.com/tachiyomiorg/tachiyomi/assets/35057681/d66d9560-e29b-44a3-a23f-839b5e03906a)

2023-11-01 13:01 UTC, merged