add page split webtoon page (alpha)
tachiyomiorg/tachiyomi pull request #4791
Opened 2021-04-07 11:13 UTC by Riztard

split very long webtoon page, to make it less lag/smoother when scrolling

*based on dual page split
*need to split more than 2 if the image is very long or make it dynamic or just split into 3

2021-04-07 12:23 UTC, ghostbear commented
Just leaving an idea for splitting it into more than two.

Instead of using `InsertPage` which only supports right and left have a data class that holds an offset, and the parent. And a pre-defined height that the class would use as height for each split of the image. This class and height variable would work as a stencil to display the image. 

---

Let us say you have an image with a height of 4500 and the stencil height of 1000. This means the code should generate four stencil pages
```
*---*
|   | ReaderPage
|   |
*---* Y=1000
|   | StencilPage(offset=1000)
|   |
*---* Y=2000
|   | StencilPage(offset=2000)
|   |
*---* Y=3000
|   | StencilPage(offset=3000)
|   |
*---* Y=4000
|   | StencilPage(offset=4000)
*---* Y=4500
```
When it detects that it is a webtoon page `ReaderPage` will get the offset from 0 to the stencil height (1000), then each stencil page will use the offset along with the stencil height to render the reset of the webtoon page. The last page may or may not be 1000 in height so it would just render what's left in this case 500.

It would still work like dual page split inserting into the adapter but it would insert multiple items instead of one.

The stencil height could be the screen height or the screen height multiplied by 2 not necessarily 1000

2021-04-07 12:30 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
> +
You probably want to have a cleanup function as well else you will end up will duplicates
https://github.com/tachiyomiorg/tachiyomi/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt#L155-L159

2021-04-09 03:01 UTC, arkon requested changes

2021-04-09 03:01 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
> +        if (isWebtoonPage) {
Short-circuit early, i.e.

```
if (!isWebtoonPage) {
  return ...
}

// Other logic
return ...
```

2021-04-09 03:01 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
> +        page?.let { newPage?.let { it1 -> viewer.onPageSplitWebtoon(it, it1) } }
Just use an if-statement to check if `page` is null, the `.let`s here aren't making it any more readable.

2021-04-09 13:55 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
> +        var inputStream = openStream
It is needed because of reassignment later when the stream is read, else the image will just be blank. But it can be replaced with `InputStream.mark()` and `InputStream.reset()` in the functions in `ImageUtil`

2021-04-09 16:00 UTC, Riztard commented
ill just let ghostbear or others to continue this 🤣
i dont even know what did i write lol
my ape brain cant handle it :harold:

2021-04-09 16:19 UTC, ghostbear commented
A monke wrote it so another monke should be able to add to it

2021-04-09 16:21 UTC, Riztard commented
> A monke wrote it so another monke should be able to add to it

apes alone weak
apes together strong

2021-04-09 16:51 UTC, ghostbear commented
I think you should be able to go through the PR review
I will go through them and add suggestions to help you out a bit

2021-04-09 18:09 UTC, ghostbear reviewed
I have made some suggestions to help you get through the PR review, it's based on arkon's comments. If you want me to explain more about why I did something in one of the suggestion just comment on them

2021-04-09 18:22 UTC, ghostbear commented
> A recent PR replaced this function with an extension function, so you could use that here too.

As for adding this, I think you should checkout 62ac664, rebase, and force push to this branch to get the extension functions

Just remember the things you changed in c64d44b

2021-04-10 11:55 UTC, Riztard commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonAdapter.kt
> +    }
> arkon: Put this alongside the other split function

its not possible right? because pager and webtoon have different adapter? 🤔

2021-04-10 12:01 UTC, Riztard commented on app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt
> +     * Check whether the image is a webtoon image (width * 3 < height), return the result and original stream
yea what if its just high quality images 🤔

2021-04-10 12:04 UTC, Riztard commented
hmm failed

2021-04-10 12:08 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
> +        adapter.onPageSplitWebtoon(currentPage, newPage, this::class.java)
To many arguments
```suggestion
        adapter.onPageSplitWebtoon(currentPage, newPage)
```

2021-04-10 13:46 UTC, arkon commented
You don't really need to rebase, the core extension functions should be available to you anyway.

2021-04-10 13:48 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonAdapter.kt
> +    fun cleanupPageSplit() {
I mean grouping `onPageSplitWebtoon` and `cleanupPageSplit` together.

2021-04-10 13:48 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
> +        val upperSide = when {
Can you try making it so it's `when (page) { ... }`?

2021-04-10 13:48 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt
> +     * Check whether the image is a webtoon image (width * 3 < height), return the result and original stream
Super hi-res images will make it lag anyway.

2021-04-10 14:03 UTC, Riztard commented on app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt
> +     * Check whether the image is a webtoon image (width * 3 < height), return the result and original stream
so if height more than what?

2021-04-10 14:05 UTC, Riztard commented on app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt
> +     * Check whether the image is a webtoon image (width * 3 < height), return the result and original stream
make it like (height > width && height > x) ?
or dont compare to width

2021-04-10 14:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/system/ImageUtil.kt
> +     * Check whether the image is a webtoon image (width * 3 < height), return the result and original stream
Kind of hard to say without any data, but I'm fine with @ghostbear's suggestion of 10,000px as a start. We could fiddle around with it more in the future. You just need to make sure that it's simple to change that predicate.

2021-04-10 15:01 UTC, Riztard commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
> +        val upperSide = when {
that sounds simple, but im not famiiar with `when` LOL

2021-04-11 19:53 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
> +        val upperSide = when {
```
when (page) {
  is InsertPage -> ...
  !is InsertPage -> ...
}
```

2021-04-11 19:54 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
> +        val upperSide = when {
Or maybe just a good old fashioned `if`/`else`.

2021-04-12 06:22 UTC, Riztard commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
> +        val upperSide = when {
like this? 🤔
https://github.com/tachiyomiorg/tachiyomi/pull/4791/commits/01a621aa7ea2c4f6d41a6968105daa7fc3e1bf2e

2021-04-16 13:00 UTC, arkon commented
@Riztard Was this ready for another round of review, or are you still iterating on it?

2021-04-16 13:33 UTC, Riztard commented
maybe, i dont know what else to do 😂
ill let someone(you) clean it :tehe:

2021-04-27 21:34 UTC, arkon commented
@ghostbear I assume you were interested in continuing this work? How did you want to do that, do you want to PR into @Riztard's branch, or do you want to create your own, or do you want me to merge this into a different branch to work off of?

2021-04-28 06:17 UTC, ghostbear commented
I will probably just create my own PR superseding this and make Riztard a co-author on the commit containing most of his logic

2021-04-28 08:47 UTC, ghostbear commented
I have tested this and the stencil page idea on my old Sony Xperia M2 Aqua which is the lowest end device I have

Riztard's PR seems to work fine just that it's a bit janky jumping around when processing/adding the pages

For my stencil page idea, it throws OOM near-instantaneous this is mostly because it does everything on IO rather than the main thread. Even if I only do two pages like Riztard's PR does it still throws OOM

I found an alternative way to reduce lag which is to use `BitmapFactory` option `inSampleSize` to basically scale down the image, but at the cost of quality. And it doesn't throw OOM as soon as it's being processed. I believe this would be a better way to approach this rather than to introduce jankiness into the `WebtoonViewer`.
Maybe even keep some of the elements of this PR in this solution where it only scales down extremely tall images

2021-08-18 16:41 UTC, FourTOne5 commented
> I have tested this and the stencil page idea on my old Sony Xperia M2 Aqua which is the lowest end device I have

Can you provide the code?

2021-08-18 17:25 UTC, ghostbear commented
> > I have tested this and the stencil page idea on my old Sony Xperia M2 Aqua which is the lowest end device I have
> 
> Can you provide the code?

It seems I have deleted the stash containing the code, so no I can't provide it.

But it is really similar to how it does dual page split except it determined how many pages it needed to split it to then loop over the original image to create the splits and inserted them into the recycler

2021-08-18 17:30 UTC, FourTOne5 commented
> then loop over the original image to create the splits and inserted them into the recycler

Where exactly were you looping it? I tried to do by looping but it didn't went as planned

2021-08-18 17:46 UTC, ghostbear commented
> > then loop over the original image to create the splits and inserted them into the recycler
> 
> Where exactly were you looping it? I tried to do by looping but it didn't went as planned

Before calling `splitWebtoon` I changed the parameters to take in an int to represent which page it was creating and remove the side parameter. Also had a global constant to represent the height of the stencil image 

So something like this:
```kt
// Global constant somewhere
val STENCIL_HEIGHT = 10_000

// Loop
val imageHeight = ImageUtil.getHeight(inputStream)
val numberOfPages = imageHeight / STENCIL_HEIGHT
for (pageIndex in 0..numberOfPages) {
  val newImage = ImageUtil.splitWebtoon(inputStream, pageIndex)
  // Handle image
}
// First image gets returned to the current WebtoonPageHolder
// The rest of the images goes to the recycler 
```

2021-08-20 08:44 UTC, FourTOne5 commented
Just wanted to clarify I'm working on this.

2021-08-21 22:16 UTC, arkon commented
Superseded by #5759

2021-08-21 22:16 UTC, closed without merging