[WIP] Add Komga as an unattended track service
tachiyomiorg/tachiyomi pull request #5049
Opened 2021-05-10 06:39 UTC by gotson

This PR is an attempt to add tracking support between Tachiyomi and Komga (server).

It works quite differently from regular tracking services. The Komga tracker can only be used for mangas that are using the Komga source. It will use the unique IDs of the manga to match it on the server, so no search dialog is necessary. A manga will be either a match, or not.

It also does not need to login to the tracking service. The TrackService will use the same OkHttp client than the Komga extension, and as such will be able to access the session cookie for a particular domain. This has the benefit of having a single Komga tracker than can track multiple instances of the Komga extension, because it relies on the URL of the manga to find the correct server and session cookie.

It is still a work in progress, i would like to add:
- support for read lists. Read Lists can be added as manga, so they should be trackable also. At the moment the code doesn't handle read lists at all, and would not find any match for a read list.
- auto-bind when adding a Komga source manga to the Tachiyomi library. Given there is no need for user interaction, auto-bind should be achievable.
- 2-way sync. This was proposed in a [PR](https://github.com/tachiyomiorg/tachiyomi/pull/3705).

Feedbacks on this WIP PR is appreciated, as I am not very familiar with Android development!

2021-05-10 07:12 UTC, gotson commented
I have added auto-bind when adding to library. This will attempt to match the manga with any UnattendedTrackService, and can be disabled by a new preference in the Tracking settings.

<img width="324" alt="Screenshot 2021-05-10 at 15 12 25" src="https://user-images.githubusercontent.com/2139133/117619698-2b0ca780-b1a2-11eb-8020-01d17f4e30e7.png">

2021-05-10 07:48 UTC, gotson commented
I have added 2-way sync for read progress. Chapters are marked as read in Tachiyomi upon tracker refresh. This will only apply to unattended tracking services though.



https://user-images.githubusercontent.com/2139133/117624060-12eb5700-b1a7-11eb-9e90-b42ee7081f02.mp4

2021-05-10 08:05 UTC, ghostbear commented
> I have added 2-way sync for read progress. Chapters are marked as read in Tachiyomi upon tracker refresh. This will only apply to unattended tracking services though.

Okay nice 👍

2021-05-10 21:41 UTC, goldbattle commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt
> +            chapter.read = index < lastChapterRead
If you read chapters out of order, then this will mark ones read as unread?

2021-05-10 21:46 UTC, goldbattle commented
This PR looks very promising and opens a way for 2way since for services which provide tracking in a very seamless manor. I am a big fan. I was wondering about your comment:
```
The TrackService will use the same OkHttp client than the Komga extension, and as such will be able to access the session cookie for a particular domain
```

Can you point to me where this is the case?
The client build is from the tracking service [here](https://github.com/tachiyomiorg/tachiyomi/pull/5049/files#diff-81a344ab9e41c8464f4c53a122c348b8f623748da273880c8b447daf9c532c0bR27-R30), and I only see the interaction directly with the extension [here](https://github.com/tachiyomiorg/tachiyomi/pull/5049/files#diff-3abcd51424f6288497b857220699c9b184308e580b01d2ced558cf681105256eR88-R104).

2021-05-11 01:12 UTC, goldbattle commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt
> +            chapter.read = index < lastChapterRead
True, and that is understandable. A thought would be to add a list of "read" chapters ids to the `Track` model which `UnattendedTrackService`s only use to sync per-chapter read status. For example in the [getTrackSearch()](https://github.com/tachiyomiorg/tachiyomi/pull/5049/files#diff-b7b82e522af71b0f5f674816ae2fe443db46cc18decfb2b3b37878dd851b5071R21-R62) this custom field could be set to an array of chapter ids which have been read. Going the other way from Tachi to Komga api the [updateProgress()](https://github.com/tachiyomiorg/tachiyomi/pull/5049/files#diff-b7b82e522af71b0f5f674816ae2fe443db46cc18decfb2b3b37878dd851b5071R64-R75) to be changed to just setting a "read / unread" boolean per chapter (unless you also track it as a single chapter number).

2021-05-11 07:33 UTC, gotson commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaPresenter.kt
> +            chapter.read = index < lastChapterRead
I just ran into that very case myself. For series with specials, i name the files so they end up last in the directory, so they don't mess up the automatic numbering of normal issues when adding new ones. This breaks the current tracking, a workaround is to keep those specials as unread for now.

I will work on a new branch with your suggestion, so we can line up another PR for later 👍🏻

2021-05-14 01:59 UTC, gotson commented
I have changed a bit the logic on server side for the computation of the last read book, now it will return the index of the last read book in a continuous fashion. So if a series has 10 books, and you read 1-3 and 6, it will still return 3. That way the read books out of order will not mess up the count.

The server will only mark books as read when receiving tracker update from Tachiyomi. I will not mark unread books as unread.

How 2-way sync works:
- retrieve the remote track with the `lastRead`
- mark local chapters as read if they were unread for chapters < `lastRead`
- update the remote tracker with a new track, composed of read chapters

So if you had books 1-2 marked as read on server, and 1-4 on Tachiyomi:
- retrieve remote track with `lastRead` = 2
- mark 1-2 as read
- update remote tracker with lastRead = 4

2021-05-19 13:09 UTC, arkon requested changes
- Is there a simpler icon for the tracker? It looks out of place.
- Do you expect the API on Komga's side to change in the future? You'll be tied tightly with app updates, which likely won't move as quickly as you need it to.

2021-05-19 13:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/track/komga/KomgaApi.kt
> +        val payload = Json.encodeToString(ReadProgressUpdateDto.serializer(), progress)
There should be an extension function that lets you drop the explicit serializer.

2021-05-19 13:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourcePresenter.kt
> +            if (prefs.autoAddTrack()) {
Nitpick: extract this out into a function

2021-05-19 13:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackHolder.kt
> +                    text = "Not supported"
Should be localized.

2021-05-19 13:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSheet.kt
> +                controller.presenter.view?.applicationContext?.toast("Source is not supported")
Should be localized.

2021-05-19 13:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSheet.kt
> +                    withUIContext { controller.presenter.view?.applicationContext?.toast("No match found") }
Should be localized.

2021-05-19 13:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSheet.kt
> +                    withUIContext { controller.presenter.view?.applicationContext?.toast("No match found") }
Should be localized.

2021-05-19 13:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSheet.kt
> +        if (item.track == null || item.service.getScoreList().isEmpty()) return
What exactly is the expectation here as the user? I just can't set the score?

2021-05-19 13:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsTrackingController.kt
> +                        if (service is NoLoginTrackService) {
Is this actually necessary? I don't see a problem with confirming even if the login is basically a no-op.

2021-05-19 13:09 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterTrackSync.kt
> +        }
Probably want to at least log something?

2021-05-20 01:21 UTC, gotson commented
> * Is there a simpler icon for the tracker? It looks out of place.

I took the one from the extension. The original Komga logo is round, you can see it at https://komga.org/. I also have the [original SVG logo](https://github.com/gotson/komga/blob/master/res/komga_text_as_path.svg), so I could probably do something with it. I'm not sure however what's so out of place when looking at the others, they don't seem to have a common trait. Please let me know !

> * Do you expect the API on Komga's side to change in the future? You'll be tied tightly with app updates, which likely won't move as quickly as you need it to.

The element (series or readlist) API is solely used to get the _title_, _summary_ and _publishing status_, but i think only the title is used in the track sheet, the summary and publishing status are used in the interactive dialog to choose the right manga to track, but that is not used here. Those APIs have been quite stable since their introduction.

There is a newly added API endpoint solely for tachiyomi tracking (`/read-progress/tachiyomi`), so the impact would be quite limited.

---

I will have a look at all your comments on the code now.

2021-05-20 01:23 UTC, gotson commented on app/src/main/java/eu/kanade/tachiyomi/data/track/komga/Komga.kt
> +        TODO("Not yet implemented: add")
the `add` function is defined in `TrackService` but never called in any common code. It is only called from inside each tracker implementation.

<img width="842" alt="Screenshot 2021-05-20 at 09 22 45" src="https://user-images.githubusercontent.com/2139133/118904708-fd1b2600-b94c-11eb-85fd-e9bb73b1ba6f.png">

I would suggest to remove it from `TrackService`.

2021-05-20 01:57 UTC, gotson commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSheet.kt
> +        if (item.track == null || item.service.getScoreList().isEmpty()) return
If the score list is empty, this will crash the app. I noticed this while coding, it probably went unnoticed since all other trackers have score.

This is because of https://github.com/tachiyomiorg/tachiyomi/blob/535abcbb8b2197faef77a6b0ba56aa4309067d4c/app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/SetTrackScoreDialog.kt#L66

There may be a better way to avoid that crash directly in `SetTrackScoreDialog` though, but given it's a pop-up dialog, we should not open the dialog at all if there's no score.

In addition to the above change, which is really to prevent a crash in case we incorrectly change other parts of the code, I added [this](https://github.com/gotson/tachiyomi/blob/622e68270b2ce94673e30d910ce65f5b206747ce/app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackHolder.kt#L55) to disable the score button entirely.

If you want to keep only the disabled one, i can remove that additional check.

2021-05-20 01:58 UTC, gotson commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsTrackingController.kt
> +                        if (service is NoLoginTrackService) {
I thought it would make the experience better. There's i no point asking to logout if you didn't ask for login. That makes the preference a simple toggle at each tap.

If you think it clutters the code i can remove it.

2021-05-20 03:00 UTC, gotson commented on app/src/main/java/eu/kanade/tachiyomi/util/chapter/ChapterTrackSync.kt
> +        }
Good catch, i added some logs for the execption.

2021-05-20 03:01 UTC, gotson commented
I have rebased, fixing some merge conflicts, and addressed the majority of your comments @arkon

2021-05-20 04:41 UTC, gotson commented
I also changed the logo for a webp version generated from the original (rounded) logo.

2021-05-22 16:05 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/track/komga/Komga.kt
> +        TODO("Not yet implemented: add")
Yeah, the tracker interface isn't that great in general.

2021-05-22 16:06 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackSheet.kt
> +        if (item.track == null || item.service.getScoreList().isEmpty()) return
It may be better to just make it not render the score selection at all if there's trackers that don't support it. The previous assumption was that all trackers support that.

2021-05-22 16:06 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsTrackingController.kt
> +                        if (service is NoLoginTrackService) {
I'm kind of split on it, but I'm fine with keeping it.

2021-05-22 16:07 UTC, arkon approved these changes

2021-05-22 16:07 UTC, merged

2021-05-22 16:08 UTC, arkon commented
Can followup in separate PRs on the comments if necessary.