Add option to hide "Updates" and "History" buttons
tachiyomiorg/tachiyomi pull request #5077
Opened 2021-05-14 10:28 UTC by simakover

Add option to hide "Updates" and "History" buttons. Add code in showBottomNav function for manipulate visibility of buttons "on a fly"

2021-05-14 10:32 UTC, CarlosEsco commented
Can you provide screenshots?

2021-05-14 10:43 UTC, simakover commented
> Can you provide screenshots?
done

2021-05-14 11:01 UTC, Riztard commented
maybe can work similar to sy/j2k reader button

2021-05-14 21:53 UTC, arkon requested changes
Sorry, I ended up pushing some changes that you'll need to rebase on. Of note, you'll need to handle both the bottom nav (as before) and the side nav (new for larger screens).

2021-05-14 21:53 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
> +        switchPreference {
Since there's more stuff related to the navigation now, we should create a group for it. We can put it under the existing Locale group, something like:

**Navigation**

- Hide bottom bar on scroll
- Updates section (default true)
- History section (default true)

2021-05-14 21:53 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
> +import androidx.core.view.*
Use explicit imports.

2021-05-15 11:49 UTC, simakover commented on app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
> +import androidx.core.view.*
resolved by commit baf38f5

2021-05-15 11:51 UTC, simakover commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsGeneralController.kt
> +        switchPreference {
resolved by commit 0e27bc7

2021-05-15 11:54 UTC, simakover commented
> Sorry, I ended up pushing some changes that you'll need to rebase on. Of note, you'll need to handle both the bottom nav (as before) and the side nav (new for larger screens).

Im manipulating bottom nav in showBottomNav fuction cause its calls for bottom_nav.
Where im can add code for manipulating side nav items?

2021-05-15 12:36 UTC, ghostbear commented
> > Sorry, I ended up pushing some changes that you'll need to rebase on. Of note, you'll need to handle both the bottom nav (as before) and the side nav (new for larger screens).
> 
> Im manipulating bottom nav in showBottomNav function cause its calls for bottom_nav.
> Where im can add code for manipulating side nav items?

You can manipulate it in the `showSideNav` function
https://github.com/tachiyomiorg/tachiyomi/blob/0e27bc7ef6848a148fe25bd5c22a1f01b6af60a1/app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt#L484-L488

And you can access the menu in the same way as you did with `bottomNav`
```kt
private fun showSideNav(visible: Boolean) {
  binding.sideNav?.let {
    it.isVisible = visible
    val navUpdates = it.menu.findItem(R.id.nav_updates)
    navUpdates.isVisible = !preferences.hideUpdatesButton().get()
    // ...
  }
}
```

You could make a function which takes in the menu to not have duplicated code 
```kt
private fun showSideNav(visible: Boolean) {
  binding.sideNav?.let {
    it.isVisible = visible
    updateNavMenu(it.menu) // Replace the code in showBottomNav with the same function call
  }
}

private fun updateNavMenu(menu: Menu) {
  val navUpdates = menu.findItem(R.id.nav_updates)
  navUpdates.isVisible = !preferences.hideUpdatesButton().get()
  val navHistory = menu.findItem(R.id.nav_history)
  navHistory.isVisible = !preferences.hideHistoryButton().get()
}
```

2021-05-15 12:57 UTC, simakover commented
@ghostbear thanks

2021-05-15 19:01 UTC, merged