Hide Start/Resume FAB unless there are unread chapters and during loading
tachiyomiorg/tachiyomi pull request #5458
Opened 2021-06-26 00:49 UTC by datreesezcup

This PR hides the Start/Resume FAB when viewing Manga info and chapters, and only shows it if there are unread chapters for the manga.

This addresses the fact that while the chapter list is loading, or when all chapters are read, the FAB is unneeded and does nothing (besides showing a Toast that there's no next chapters), as well as being slightly misleading with it's label. (Such as showing "Start" when there are no chapters, or "Resume" when there's currently no more chapters to read).

2021-07-10 19:52 UTC, arkon requested changes

2021-07-10 19:52 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
>              }
Let's just remove the dead code.

2021-07-10 19:52 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaController.kt
>          }
```kotlin
val context = view?.context
if (context != null) {
  actionFab?.isVisible = chapters.any { !it.read }
  if (chapters.any { it.read }) {
    actionFab?.text = context.getString(R.string.action_resume)
  }
}

2021-07-12 15:27 UTC, datreesezcup commented
Changes made and committed!

2021-07-12 15:48 UTC, merged