Add ability to open induvidual FAQ and Guide, and Changelog for extension
tachiyomiorg/tachiyomi pull request #6469
Opened 2022-01-15 14:59 UTC by ghostbear

Depends on (TODO)

Adds the ability to open individual FAQ and Guide, and Changelog on extension detail screen. When the user presses the FAQ and Guide button they will be taken to the `README.md` located in the extension module else it will take them to the Tachiyomi website for general extension FAQ. And when the user presses the commit history button they will be taken to the `CHANGELOG.md` located in the extension module else it will take them to the commit history for that extension

Does this introduce breaking changes: no

Examples where the link takes the user
- FAQ and Guides
  - [MangaDex](#TODO)
- Changelog
  - [Komga](#TODO)

2022-01-15 15:15 UTC, henrik9999 commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt
> +private const val URL_EXTENSION_BLOB = "https://github.com/ghostbear/tachiyomi-extensions/blob/master"
Wrong URL

2022-01-15 15:18 UTC, curche commented on app/src/main/java/eu/kanade/tachiyomi/extension/api/ExtensionGithubApi.kt
> +    val hasChangelog: Int = 0,
Can this not be `Boolean` like at other places?

2022-01-15 16:35 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt
> +private const val URL_EXTENSION_BLOB = "https://github.com/ghostbear/tachiyomi-extensions/blob/master"
Eh no, this is a base that is built upon in https://github.com/tachiyomiorg/tachiyomi/blob/8e291661ab6e246abb5e3c758695cefa16e029ef/app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt#L225-L226 and https://github.com/tachiyomiorg/tachiyomi/blob/8e291661ab6e246abb5e3c758695cefa16e029ef/app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt#L250-L251

2022-01-15 16:42 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/extension/api/ExtensionGithubApi.kt
> +    val hasChangelog: Int = 0,
I just followed what `nsfw` did and yes it could probably be a `Boolean`. But to not make it confusing and have them as `Boolean` while `nsfw` is not I rather keep them as `Int`

2022-01-22 15:30 UTC, arkon requested changes

2022-01-22 15:30 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt
> +            }
Could probably reduce some repetition on how all of these URLs are being created.

2022-01-22 15:30 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt
>      private fun openCommitHistory() {
Can you rename this to something like `openChangelog`?

2022-01-22 15:30 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt
>          val url = when {
Can you add a comment to say that we're falling back to the commit history if there's no explicit changelog?

2022-01-22 15:30 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/details/ExtensionDetailsController.kt
> +    private fun openExtensionReadme() {
`openReadme`?

2022-01-22 15:30 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="action_faq_and_guides">Open FAQ and Guides</string>
Maybe remove the "Open"?

2022-01-22 19:17 UTC, arkon approved these changes

2022-01-22 19:17 UTC, merged