Fix Global and extension search input accepts formatted text #6495
tachiyomiorg/tachiyomi pull request #6501
Opened 2022-01-25 01:42 UTC by afreakyelf

2022-01-26 14:26 UTC, arkon reviewed
This seems to have a negative impact on the actual performance (e.g., it's noticeably laggy when inputting text or holding backspace).

2022-01-26 14:29 UTC, afreakyelf commented
Do you have anything in mind that we can implement or make changes to my PR?

2022-01-26 14:36 UTC, arkon commented
You may be able to check if there's actually formatting (check for presence of some spans?) or potentially check if the pre and post-removal strings are the same (which I assume would be different?) prior to setting the selection to reset the cursor (which is what I think would be causing the "lag").

2022-01-26 14:37 UTC, afreakyelf commented
Sure let me give it a try.

2022-01-26 16:36 UTC, afreakyelf commented
Hi @arkon, I have pushed the change and it seems to be working now. Can have a look please.

2022-01-27 03:49 UTC, arkon requested changes

2022-01-27 03:49 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +        searchAutoComplete.addTextChangedListener(object : TextWatcher {
We could probably move this to be within `TachiyomiSearchView`.

2022-01-27 03:49 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +                // TODO("Not yet implemented")
Remove TODOs

2022-01-27 03:49 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +            override fun afterTextChanged(s: Editable?) {
Use more meaningful variable names

2022-01-27 03:49 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +                val spannable: Array<StyleSpan> = s!!.getSpans(
Try to avoid `!!` if this really is nullable

2022-01-27 03:49 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +                    0, 5,
Why 5?

2022-01-27 03:49 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +                if (spannable.isNotEmpty()) {
This check isn't really necessary

2022-01-27 03:49 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +                    for (i in spannable.indices) {
Use something like `.forEach {}` instead of a for loop

2022-01-27 03:49 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +    // To format the text
This is misleading, it removes formatting. Can just remove it and rename the function to something more meaningful (e.g. `removeFormatting`)

2022-01-27 04:02 UTC, afreakyelf commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +        searchAutoComplete.addTextChangedListener(object : TextWatcher {
I tried but addTextChangedListener is not populating. Rest changes I have made. Please check again

2022-01-27 04:05 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +        // TO remove formatting from clipboard text #6495
```suggestion
        // Remove formatting from pasted text
```

2022-01-27 04:05 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +                }
```suggestion
                editable.getSpans(0, editable.length, StyleSpan::class.java)
                    .forEach { editable.removeSpan(it) }
```

2022-01-27 04:08 UTC, afreakyelf commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +                }
Done, Please check.

2022-01-27 04:26 UTC, afreakyelf commented on app/src/main/java/eu/kanade/tachiyomi/ui/base/controller/SearchableNucleusController.kt
> +                }
Can you please approve it if nothing is left to modify.

2022-01-27 04:37 UTC, arkon approved these changes

2022-01-27 04:37 UTC, merged

2022-01-29 22:53 UTC, alessandrojean commented
Just letting you know that your modifications did not fix the issue, it still happens in r4118.

![SmartSelect_20220129-194812_Tachiyomi](https://user-images.githubusercontent.com/14254807/151680137-76983644-a134-47fa-87bd-539383d430b1.jpg)

2022-01-29 22:58 UTC, arkon commented
Odd, I thought I tested it too but maybe the text I copied wasn't formatted.