Show number of all unique mangas in all categories
tachiyomiorg/tachiyomi pull request #6679
Opened 2022-02-19 15:10 UTC by ComBeat

This implements the feature request #6522.
A method was implemented that counts all mangas in the library uniquely and that number is shown in the action bar, even if categories and the number of items are enabled.

![default](https://user-images.githubusercontent.com/15837468/154806564-d475f4f4-d5b5-488d-b5e0-f62ac0af0c0d.png)

2022-02-20 15:13 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
> +    private fun getTotalLibraryCount(mangaMap: Map<Int, List<LibraryItem>>): Int {
Instead of recalculating it every time "Title" is updated i think it'll be better to include the value in `Library` class.

2022-02-20 23:45 UTC, vengiare commented
Can I ask what does it look like on the Library sheet

2022-02-21 13:34 UTC, ComBeat commented
> Can I ask what does it look like on the Library sheet

@vengiare Look at the screenshot above and then look at the title bar. The number right next to "Library" is what has been implemented. In this case there are 12 unique mangas in the library.

2022-02-21 13:38 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
> +    private fun getTotalLibraryCount(mangaMap: Map<Int, List<LibraryItem>>): Int {
I agree. I'll do that.

2022-02-21 18:15 UTC, vengiare commented
I mean how is the feature enabled? What does the toggle look like in the filter sheet.

#

It would also have conflicts with this specific configuration, which show manga count for the current category.

![Screenshot_20220222-021319](https://user-images.githubusercontent.com/63973749/155008132-f24fd57d-37d6-4a71-80b3-e0ab4af9dc8e.png)

2022-02-22 00:43 UTC, ComBeat commented
> I mean how is the feature enabled? What does the toggle look like in the filter sheet.

So far there is no seperate setting for this. This feature can be enabled  with "Show number of items".
> It would also have conflicts with this specific configuration, which show manga count for the current category.

I've tested this pr and so far there have been no conflicts with that specific configuration.
With that configuration it looks like this.
![image](https://user-images.githubusercontent.com/15837468/155042973-8641e745-625d-4dba-809b-354ada4a3c2b.png)

2022-02-22 04:20 UTC, vengiare commented
Maybe something like this?

![image](https://user-images.githubusercontent.com/63973749/155062296-18125e4c-5013-4bc0-acaa-db364e3f3cbb.png)
![image](https://user-images.githubusercontent.com/63973749/155062504-e9ba1fef-8b0e-409e-8552-fe5892e8f39b.png)

2022-02-27 21:59 UTC, ComBeat commented
That's a good idea. I will implement that in the next few days.

2022-03-05 19:35 UTC, ComBeat commented
I've moved the library count to the class `Library` and added a setting for enabling/disabling the library count.

2022-03-05 20:09 UTC, ComBeat commented
> Maybe something like this?

Right now it's implemented exactly like you suggested in the screenshot, with `Show number of library items` being disabled if `Show number of items per category` is disabled.
But when I think about it, it makes more sense to not let getting it disabled and instead handle them as 2 independent settings. 
What do you think @vengiare?

2022-03-06 05:44 UTC, FourTOne5 commented
Any non-eng strings are handled by weblate revert changes on those.

2022-03-06 13:32 UTC, ComBeat commented
> Any non-eng strings are handled by weblate revert changes on those.

Done.

2022-03-08 05:18 UTC, vengiare commented
> with `Show number of library items` being disabled if `Show number of items per category` is disabled.

Wait what? My idea was `Show number of library items` will be disabled if >> `Show category tabs` << is disabled.

#

Also on second thought, "Show number of library items" can be renamed to "Show total library count" or something,

2022-03-08 20:37 UTC, ComBeat commented
> My idea was Show number of library items will be disabled if >> Show category tabs << is disabled.

I've misread your post. Sorry.
I've implemented it now exactly like you suggested.

![image](https://user-images.githubusercontent.com/15837468/157319406-124345f7-d8e5-4c2e-887e-98ff7907f12a.png)
![image](https://user-images.githubusercontent.com/15837468/157319454-45fdcf26-a73c-4efb-91b1-886650274c90.png)
![image](https://user-images.githubusercontent.com/15837468/157319506-a9e48500-2138-4045-9b3d-42b9f27ef68e.png)

2022-03-09 11:11 UTC, FourTOne5 requested changes

2022-03-09 11:11 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun categoryNumberOfItems() = flowPrefs.getBoolean("display_number_of_category_items", false)
since the key was changed from `display_number_of_items` to `display_number_of_category_items` you might want to migrate the value in `Migrations.kt`

2022-03-09 11:11 UTC, FourTOne5 commented on app/src/main/res/values/strings.xml
> +    <string name="action_display_show_number_of_library_items">Show total number of library items</string>
`Show number of items in library`?

2022-03-09 11:11 UTC, FourTOne5 commented on app/src/main/res/values/strings.xml
> +    <string name="action_display_show_number_of_category_items">Show number of items per category</string>
`Show number of items in category`?

2022-03-09 11:11 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
> +                title += if (title == resources?.getString(R.string.label_library)) {
Checking if the string is same might not be a good idea.

2022-03-26 19:31 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun categoryNumberOfItems() = flowPrefs.getBoolean("display_number_of_category_items", false)
So far I have no idea how to do that, but I will continue to look into it.

2022-03-26 19:34 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
> +                title += if (title == resources?.getString(R.string.label_library)) {
I'm also not quite content with this solution. I'll try something different.

2022-03-26 19:36 UTC, ComBeat commented on app/src/main/res/values/strings.xml
> +    <string name="action_display_show_number_of_library_items">Show total number of library items</string>
It's shorter than the current phrase.
I will apply that.

2022-05-02 10:58 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
> +                title += if (title == resources?.getString(R.string.label_library)) {
It's now checked against the preference `preferences.categoryTabs().get()`.

2022-05-05 22:53 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun categoryNumberOfItems() = flowPrefs.getBoolean("display_number_of_category_items", false)
@FourTOne5 I integrated it into `Migrations.kt`. Please take a look at it.

2022-05-24 10:02 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/tachiyomi/Migrations.kt
> +                }
```suggestion
                val displayNumberOfItems = flowPrefs.getBoolean("display_number_of_items", false)
                if (displayNumberOfItems)
                    preferences.categoryNumberOfItems().set(false)
                }               
```
Also move this another if block after bumping app version

2022-05-28 13:20 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
> +            private val showNumberOfCategoryItems = Item.CheckboxGroup(R.string.action_display_show_number_of_category_items, this)
I'm actually not sure if I want to have separate settings for this. This change would be a lot simpler without it.

2022-05-28 13:20 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
> +    private fun getTotalLibraryCount(mangaMap: Map<Int, List<LibraryItem>>): Int {
You should be able to just get all the map values (`mangaMap.values`) as a flattened list, then get all the distinct items (`distinctBy`).

2022-05-28 13:20 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
> -                    else -> {}
Don't remove this, the compiler warns about it.

2022-05-28 13:20 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryAdapter.kt
> +                notifyDataSetChanged()
Is this actually necessary?

2022-05-29 14:30 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
> -                    else -> {}
Fixed

2022-05-29 19:51 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
> +            private val showNumberOfCategoryItems = Item.CheckboxGroup(R.string.action_display_show_number_of_category_items, this)
It'd be definitely simpler.  
It's already implemented, but if you as a member say, that one setting is better, I'll revert it.

2022-05-29 20:13 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryAdapter.kt
> +                notifyDataSetChanged()
The compiler complained, if there was no set block.
I just removed the set block and the compiler isn't complaining anymore.
I remove it.

2022-05-29 20:41 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/Migrations.kt
> +                }
Are you sure that ```display_number_of_items``` works?
Or did you mean ```display_number_of_category_items```?
In ```PreferencesHelper.kt``` the preference ```display_number_of_items``` was renamed to ```display_number_of_category_items```.

2022-05-29 21:06 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/Migrations.kt
> +                }
No need to rename the preference if we don't introduce a new one.

2022-05-29 23:34 UTC, ComBeat commented on app/src/main/java/eu/kanade/tachiyomi/Migrations.kt
> +                }
With this pr ```display_number_of_library_items``` is new.

2022-06-04 16:53 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/Migrations.kt
> +                }
Right, but I suggested not adding a new setting.

2022-08-29 18:34 UTC, arkon commented
Superseded by 8a3a7418d055b500517ef6c9c5623328ae01bc10

2022-08-29 18:34 UTC, closed without merging