Feature request landscape padding
tachiyomiorg/tachiyomi pull request #6706
Opened 2022-02-27 10:28 UTC by PRASHANTBHADORIYA

Created a slider in custom filter settings which allows us to adjust landscape side padding.

2022-03-02 12:57 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
> +        binding?.toolbar?.setNavigationOnClickListener(null)
This is not related to PR.

2022-03-02 13:03 UTC, FourTOne5 commented
Also delete the `.vs` folder and why is this only in landscape mode?

2022-03-02 14:10 UTC, PRASHANTBHADORIYA commented on app/src/main/res/layout-land/reader_activity.xml
> +                        See https://stackoverflow.com/questions/15701767/android-thumb-is-not-centered-in-seekbar
It's just the landscape variation of the general file which is for both portrait and landscape and so I haven't made any changes to it.

2022-03-02 14:11 UTC, PRASHANTBHADORIYA commented
> Also delete the `.vs` folder and why is this only in landscape mode?

Thanks, I forgot to delete those files, also its only on landscape mode because the PR only asked for it in landscape and you don't really need side padding in portrait mode.

2022-03-02 14:12 UTC, PRASHANTBHADORIYA commented on app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
> +        binding?.toolbar?.setNavigationOnClickListener(null)
Yeah, that was debugging mode and since its getting compiled here, I will make sure to delete it.

2022-03-02 14:15 UTC, FourTOne5 commented
> > Also delete the `.vs` folder and why is this only in landscape mode?
> 
> Thanks, I forgot to delete those files, also its only on landscape mode because the PR only asked for it in landscape and you don't really need side padding in portrait mode.

Who said i don't xD

2022-03-02 14:37 UTC, PRASHANTBHADORIYA commented on app/src/main/res/layout/reader_color_filter_settings.xml
> +        <!-- Landscape padding -->
I thought this was the best place available to add this and adding it somewhere else would make it look too weird.

2022-03-02 14:43 UTC, xwarxd commented
Thanks I was really waiting for this feature to come here someday and cant be more happy :)

2022-03-02 14:47 UTC, PRASHANTBHADORIYA reviewed
Thanks for the work.

2022-03-02 14:47 UTC, PRASHANTBHADORIYA commented
> Thanks I was really waiting for this feature to come here someday and cant be more happy :)

great

2022-03-02 19:57 UTC, jferdous70 commented
could you please make this a global setting too, and not just per manga? those of us who use padding, tend to use it for everything. it would be very tedious to do it for every manga one by one.

if it's already global then ignore. and thanks I really appreciate!

2022-03-02 20:44 UTC, ghostbear requested changes

2022-03-02 20:44 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
> +            binding.landscapeReaderContainer?.setPadding(value, 0, value, 0)
Don't know if this is the best way to set padding as it shrinks the area for tapping making it extremely hard to use. Also, this also makes so the background behind the image follows the app theme rather than the reader background color.

It would probably be better if the padding was set to the `PagerViewHolder` like it is done for Webtoon `Side Padding` in `WebtoonViewHolder`

Video is showing the two issues


https://user-images.githubusercontent.com/6576096/156446027-06549054-769e-4a97-9555-ab3945c019fb.mp4

2022-03-03 03:45 UTC, arkon reviewed
Would need to add it to the regular settings controller too.

2022-03-03 03:45 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun landscapePaddingValue() = flowPrefs.getInt("landscape_Padding_Value", 0)
Can you group the two new preferences together and use lower casing consistently?

2022-03-03 03:45 UTC, arkon commented on app/src/main/res/layout-land/reader_activity.xml
> +                        See https://stackoverflow.com/questions/15701767/android-thumb-is-not-centered-in-seekbar
I don't understand this reply. Why are you adding a landscape layout at all?

2022-03-03 03:45 UTC, arkon commented on app/src/main/res/layout/reader_color_filter_settings.xml
> +        <!-- Landscape padding -->
It'd logically make sense in the same tab as the existing webtoon padding setting.

2022-03-03 03:45 UTC, arkon commented on app/src/main/res/layout/reader_color_filter_settings.xml
> +        <!-- Red filter -->
Don't move this.

2022-03-03 03:45 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="landscape_padding">Landscape padding</string>
Please place this close to the other padding setting.

2022-03-03 03:45 UTC, arkon commented on app/src/main/res/layout/reader_color_filter_settings.xml
> +            android:layout_marginTop="16dp"
No need to change this.

2022-03-03 04:46 UTC, PRASHANTBHADORIYA commented on app/src/main/res/layout-land/reader_activity.xml
> +                        See https://stackoverflow.com/questions/15701767/android-thumb-is-not-centered-in-seekbar
> I don't understand this reply. Why are you adding a landscape layout at all?

Bs. The PR says that he want padding in landscape mode if i hadn't made the landscape layout so the padding would applied to portrait mode as well which is not the request

2022-03-03 04:49 UTC, PRASHANTBHADORIYA commented
> could you please make this a global setting too, and not just per manga? those of us who use padding, tend to use it for everything. it would be very tedious to do it for every manga one by one.
> 
> if it's already global then ignore. and thanks I really appreciate!
It's my pleasure

2022-03-03 04:49 UTC, PRASHANTBHADORIYA commented
> could you please make this a global setting too, and not just per manga? those of us who use padding, tend to use it for everything. it would be very tedious to do it for every manga one by one.
> 
> if it's already global then ignore. and thanks I really appreciate!

It's my pleasure

2022-03-03 04:57 UTC, FourTOne5 commented on app/src/main/res/layout-land/reader_activity.xml
> +                        See https://stackoverflow.com/questions/15701767/android-thumb-is-not-centered-in-seekbar
> > I don't understand this reply. Why are you adding a landscape layout at all?
> 
> Bs. The PR says that he want padding in landscape mode if i hadn't made the landscape layout so the padding would applied to portrait mode as well which is not the request

Dude just add it to combined layout and programmitacally make it not visible.

2022-03-03 08:56 UTC, PRASHANTBHADORIYA commented on app/src/main/res/layout-land/reader_activity.xml
> +                        See https://stackoverflow.com/questions/15701767/android-thumb-is-not-centered-in-seekbar
> > > I don't understand this reply. Why are you adding a landscape layout at all?
> > 
> > 
> > Bs. The PR says that he want padding in landscape mode if i hadn't made the landscape layout so the padding would applied to portrait mode as well which is not the request
> 
> Dude just add it to combined layout and programmatically make it not visible.

I don't think there is any problem in making the landscape layout the feature i added is working that all matters

2022-05-28 13:35 UTC, arkon commented
Closing as it seems abandoned. Feel free to reopen if you decide to address the comments.

2022-05-28 13:35 UTC, closed without merging