feat: add read last read chapter shortcut
tachiyomiorg/tachiyomi pull request #6861
Opened 2022-04-03 19:25 UTC by Pierre-Monier

Add the feature request in this [issue](https://github.com/tachiyomiorg/tachiyomi/issues/6784)

I add another shortcut, and a method on the HistoryController to open the ReaderActivity with the last read chapter

2022-04-08 20:31 UTC, arkon requested changes

2022-04-08 20:31 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="cant_open_last_read_chapter">Unable to open the last read chapter</string>
It either opens an in-progress or the next unread chapter, so this is a bit misleading. It should be something like "No unread chapter for <manga name>".

2022-04-10 02:34 UTC, Riztard commented
link the issue to this pr btw

2022-04-10 08:55 UTC, Pierre-Monier commented
> link the issue to this pr btw

I can't link the issue manually, and I don't put any automatic link keyword on the description. I try to edit the description to add a "fix", which is a keyword that automatically link issue to pull request but it doesn't seems to work

*just a test*

Fix [this issue](https://github.com/tachiyomiorg/tachiyomi/issues/460)

2022-04-10 09:29 UTC, Pierre-Monier commented on app/src/main/res/values/strings.xml
> +    <string name="cant_open_last_read_chapter">Unable to open the last read chapter</string>
I put the "No unread chapter for" message if we can access the manga name, otherwise it displays "Unable to open last read chapter"

2022-04-10 13:09 UTC, FourTOne5 commented
> > link the issue to this pr btw
> 
> I can't link the issue manually, and I don't put any automatic link keyword on the description. I try to edit the description to add a "fix", which is a keyword that automatically link issue to pull request but it doesn't seem to work

Change it to `Fixes #6784` instead of Fix this [issue](https://github.com/tachiyomiorg/tachiyomi/issues/6784)

2022-04-13 22:38 UTC, arkon requested changes

2022-04-13 22:38 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="no_last_read_chapter">No unread chapter for</string>
You should use a placeholder in the string instead of concatenating the strings so that this can be localized properly.

2022-04-16 10:20 UTC, Pierre-Monier commented on app/src/main/res/values/strings.xml
> +    <string name="no_last_read_chapter">No unread chapter for</string>
fix with last commit

2022-04-16 14:01 UTC, arkon requested changes

2022-04-16 14:01 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt
> +            activity?.toast(String.format(resResources.getString(R.string.no_last_read_chapter), mangaName))
Don't use `String.format`; `getString` takes in the args directly.

2022-04-16 14:01 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt
> +        val resResources = resources
You can just use `activity`. You can do `val activity = activity ?: return` as the first line to avoid it being nullable when you use it.

2022-04-17 05:13 UTC, Pierre-Monier commented on app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt
> +        val resResources = resources
fix in last commit

2022-04-17 05:13 UTC, Pierre-Monier commented on app/src/main/java/eu/kanade/tachiyomi/ui/recent/history/HistoryController.kt
> +            activity?.toast(String.format(resResources.getString(R.string.no_last_read_chapter), mangaName))
fix in last commit

2022-04-17 15:34 UTC, arkon commented
Sorry, you'll need to rebase on top of some other history controller changes. 😅

2022-05-30 12:03 UTC, arkon commented
Superseded by #7230

2022-05-30 12:03 UTC, closed without merging