Update Skip Updating preference strings.
tachiyomiorg/tachiyomi pull request #6900
Opened 2022-04-11 10:46 UTC by FourTOne5

In dialog -
```
Skip updating titles
- with unread chapter
- that hasn't been started
- with 'Complete' status
```

In summary -
```
Skip updating titles
with unread chapter, with 'Complete' status
```
Closes #6699

Co-authored-by: Marco <76596575+SrW0nka@users.noreply.github.com>

2022-04-11 22:09 UTC, specterflare commented
Shouldn't it be "that _haven't_ been started"?

2022-04-13 21:50 UTC, arkon requested changes

2022-04-13 21:50 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="pref_update_only_completely_read">with unread chapter</string>
```suggestion
    <string name="pref_update_only_completely_read">With unread chapter(s)</string>
```

2022-04-13 21:50 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="pref_update_only_non_completed">with \'Completed\' status</string>
```suggestion
    <string name="pref_update_only_non_completed">With \"Completed\" status</string>
```

2022-04-13 21:50 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="pref_update_only_started">that haven\'t been started</string>
```suggestion
    <string name="pref_update_only_started">That haven\'t been started</string>
```

2022-04-13 22:35 UTC, merged