Auto split long images feature [Replacement of #7010]
tachiyomiorg/tachiyomi pull request #7029
Opened 2022-04-28 00:34 UTC by saud-97

Added a feature to optimize downloaded chapters reading performance and stability 
Related to: https://github.com/tachiyomiorg/tachiyomi/issues/6973 https://github.com/Jays2Kings/tachiyomiJ2K/issues/1211

- This is a replacement for https://github.com/tachiyomiorg/tachiyomi/pull/7010 since I needed to change the source repo to continue maintaining the code.

2022-05-01 00:09 UTC, saud-97 commented
I would be glad if someone could provide a review on this. So far in my testing this feature is working seamlessly.

2022-05-01 00:12 UTC, Riztard commented
no issue for now

2022-05-02 02:50 UTC, arkon requested changes

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> -
Please keep the empty lines, it keeps the code readable.

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +                Bitmap.createScaledBitmap(bitmap, bitmap.width, bitmap.height, true)
Use `BitmapCompat.createScaledBitmap` instead, it should perform better.

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +            // I noticed 1000px runs smoother than screen height below, will keep it  until someone can discover a more optimal number
Don't refer to "I" in the comments. Also, what's the relevance here? Doesn't look like you kept 1000px anyway.

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +        val imageFile = tmpDir.listFiles()!!.find { it.name!!.startsWith("$filename.") } ?: return
This should probably be an error if it can't find the page for some reason.

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +        if (ratio > 3) {
You should make a method in `ImageUtil` similar to `isDoublePage`.

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +            // xCord and yCord are the pixel positions of the image splits
"Coord"

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +                    // Compress the bitmap and save in jpg format
You should short circuit all of this if it's an animated image then. You can check with `ImageUtil.isAnimatedAndSupported`.

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +                    stream.close()
Use `.use {}` on `stream` instead to ensure it gets closed even if something fails.

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +                    File(splitPath).delete()
What if the file doesn't exist?

2022-05-02 02:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun splitLongImages() = flowPrefs.getBoolean("split_long_images", true)
Should be tall, rather than long. Same goes for the associated strings/IDs/etc.

2022-05-02 02:50 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="split_long_images">Auto split long images</string>
"Automatically split tall images"

2022-05-02 02:50 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="split_long_images_summary">Enabling this will improve reader performance by splitting long images. It is recommended to keep this turned on.</string>
"Improves reader performance."

2022-05-02 23:11 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +            // I noticed 1000px runs smoother than screen height below, will keep it  until someone can discover a more optimal number
I will delete it, I wasn't able to find a way to discover the optimal value so I thought if someone here could suggest.

2022-05-02 23:19 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> -
Done

2022-05-02 23:54 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +        if (ratio > 3) {
I have done `isTallImage `method there which checks ratio

2022-05-02 23:56 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +                    File(splitPath).delete()
`File.delete() `doesn't throw if file doesn't exist and doesn't throw if there is an I/O error. do you want me to use `Files.deleteIfExists() `to throw on I/O errors? It doesn't really matter imo

2022-05-02 23:56 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun splitLongImages() = flowPrefs.getBoolean("split_long_images", true)
Done

2022-05-03 00:10 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +                    stream.close()
That's a nice suggestion. I will start using the `.use {}`extension method whenever possible. I'm used to C# `using ()` but didn't know the alternative in Kotlin.

2022-05-03 00:11 UTC, saud-97 commented on app/src/main/res/values/strings.xml
> +    <string name="split_long_images_summary">Enabling this will improve reader performance by splitting long images. It is recommended to keep this turned on.</string>
Done, I also added the word "on download" toward the end of the sentence to remind the user how it works.

2022-05-03 00:14 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +            // xCord and yCord are the pixel positions of the image splits
Done

2022-05-03 00:32 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +                    // Compress the bitmap and save in jpg format
Done

2022-05-03 02:09 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +        if (ratio > 3) {
I would like to note that I had removed the line    `imageStream.reset() ` because it throws when I use it in this way. `isTallImage(imageFile.openInputStream())` Not sure if it's okay to emit `reset()` in this case.

2022-05-03 02:31 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +                Bitmap.createScaledBitmap(bitmap, bitmap.width, bitmap.height, true)
I also noticed that I can use the recycle() for bitmaps but I'm not sure if it's needed since I didn't notice any issues in memory or heap.

2022-05-03 02:31 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +                    stream.close()
I also noticed that I can use the recycle() for bitmaps but I'm not sure if it's needed since I didn't notice any issues in memory or heap.

2022-05-03 02:36 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
> +        val imageFile = tmpDir.listFiles()!!.find { it.name!!.startsWith("$filename.") } ?: return
Regardless, I put a notifier.onError call there just in case.

2022-05-04 02:55 UTC, saud-97 commented
I have finished the requested changes btw.

2022-05-04 13:14 UTC, arkon requested changes
Let's default this to off for now until it's tested by more people.

2022-05-04 13:14 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="split_tall_images_summary">Enabling this improves reader performance by splitting tall images on download. It is recommended to keep this turned on.</string>
```suggestion
    <string name="split_tall_images_summary">Improves reader performance by splitting tall downloaded images.</string>
```

2022-05-04 13:14 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun splitTallImages() = flowPrefs.getBoolean("split_tall_images", true)
```suggestion
    fun splitTallImages() = flowPrefs.getBoolean("split_tall_images", false)
```

2022-05-04 16:20 UTC, saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun splitTallImages() = flowPrefs.getBoolean("split_tall_images", true)
Ok sure.

2022-05-04 16:29 UTC, saud-97 commented
I honestly don't have much experience with garbage collector but I recall bitmap has a recycle method which should help. But in current status it is splitting each page one by one and on case of failure it will skip splitting the page and should continue to try to split the remaining pages. I think let us test it for now and can optimize it further later if needed.

2022-05-07 02:17 UTC, merged