Remove source lang on migrate screen also seperate removed source on alphabetical sort
tachiyomiorg/tachiyomi pull request #7041
Opened 2022-04-29 10:58 UTC by FourTOne5

Before:
![image](https://user-images.githubusercontent.com/59261191/165931890-f9320b59-fbd6-4014-bb15-ab6c92d83005.png)
After:
![image](https://user-images.githubusercontent.com/59261191/165932058-ef783195-05fc-43fe-9b69-5ac0b984365f.png)

2022-04-29 11:16 UTC, ghostbear requested changes

2022-04-29 11:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/presentation/source/components/BaseSourceItem.kt
> -    content: @Composable RowScope.(Source) -> Unit = defaultContent,
`content` should be last. As it's the primary content for this composable and will allow to move the lambda out of parameters

2022-04-29 11:21 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/presentation/source/components/BaseSourceItem.kt
> -    content: @Composable RowScope.(Source) -> Unit = defaultContent,
> and will allow to move the lambda out of parameters
How?

2022-04-29 11:25 UTC, ghostbear commented on app/src/main/java/eu/kanade/presentation/source/components/BaseSourceItem.kt
> -    content: @Composable RowScope.(Source) -> Unit = defaultContent,
Kotlin allows the last lambda to be moved outside of the parameters

Before your changes 
```kt
BaseSourceItem(
  source = source
) {
  // New content
}
```

With your changes 
```kt
BaseSourceItem(
  source = source,
  content = {
    // New content
  }
) {
  // New actions
}
```

2022-04-29 11:28 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/presentation/source/components/BaseSourceItem.kt
> -    content: @Composable RowScope.(Source) -> Unit = defaultContent,
Ahh i see

2022-04-29 11:29 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/presentation/source/components/BaseSourceItem.kt
> -    content: @Composable RowScope.(Source) -> Unit = defaultContent,
Ahh i see

2022-04-29 11:42 UTC, ghostbear approved these changes
I feel like this should just be an overriding of `content`, but I will allow it

2022-04-29 12:05 UTC, arkon approved these changes

2022-04-29 12:59 UTC, arkon commented
Any reason why this is still a draft?

2022-04-29 13:16 UTC, FourTOne5 commented
> Any reason why this is still a draft?

To change the variable name `showLanguage` to `showLanguageInContent` cause it's only used there. But ik not on my PC now.

2022-04-30 07:30 UTC, FourTOne5 commented
Ready for merge

2022-04-30 12:33 UTC, merged