Add option to reset viewer flags
tachiyomiorg/tachiyomi pull request #7062
Opened 2022-05-02 11:30 UTC by FourTOne5

Closes #3277

2022-05-03 13:24 UTC, arkon reviewed
Would it make sense to reset the default settings too, or have the resetting respect what's actually set as default?

2022-05-03 13:24 UTC, arkon commented on app/src/main/java/eu/kanade/data/manga/MangaRepositoryImpl.kt
> +            logcat(throwable = e)
This should actually have the level set to error. I missed that in the other PRs.

2022-05-03 13:24 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt
> +        if (activity == null) return
`val activity = activity ?: return`

Then it won't be nullable below.

2022-05-03 13:24 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt
> +        val isSuccesful = runBlocking { mangaRepository.resetViewerFlags() }
May want to run this on the IO thread instead.

2022-05-10 21:12 UTC, arkon requested changes

2022-05-10 21:12 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt
> +                val resouurceString = if (isSuccesful) {
Typo

2022-05-10 21:12 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt
> +            activity.toast(R.string.webview_data_deleted)
It actually may be possible for the activity to be gone by this point since it does take a bit of time to delete the data.

2022-05-10 21:12 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="pref_reset_viewer_flags_succesful">Viewer flags reset was succesful</string>
The "was succesful" part is redundant. Also, it's "successful".

2022-05-10 21:12 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="pref_reset_viewer_flags">Reset Viewer Flags</string>
Don't capitalize each word

2022-05-11 08:02 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt
> +            activity.toast(R.string.webview_data_deleted)
Even if it's stored in another variable?

2022-05-12 02:35 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsAdvancedController.kt
> +            activity.toast(R.string.webview_data_deleted)
I'm not entirely sure what happens in the case that it's referencing a dead activity.

2022-05-12 13:00 UTC, merged