Fix removing manga from library reverts during global update
tachiyomiorg/tachiyomi pull request #7063
Opened 2022-05-02 12:02 UTC by FourTOne5

Fixes #3281

2022-05-03 13:19 UTC, arkon requested changes

2022-05-03 13:19 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
> +        ioScope.cancel()
This has actually been null and caused crashes before, despite what the lifecycles would lead you to believe.

2022-05-03 13:19 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
> +            val dbManga = db.getManga(manga.id!!).executeAsBlocking()
Can just return empty lists here rather than continuing to get the chapters.

Should also:
- Do a short-circuit at the beginning of `updateManga` to avoid updating at all if it's no longer in the library at that point
- Just check prior to calling `syncChaptersWithSource`, since there's no point in updating the chapter data if it's not in the library anymore

2022-05-04 02:15 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
> +                                        }
Should probably still categorize the entries for everything it fails to pass instead of short-circuiting at each one.

2022-05-04 02:15 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
> +                                ) { mangaWithNotif ->
Try to avoid having so many unrelated changes in a PR in the future so that they're easier/quicker to review.

2022-05-04 02:17 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateService.kt
> +                                ) { mangaWithNotif ->
i'll keep that in mind

2022-05-07 02:15 UTC, merged