Local Source - qol, cleanup and cover related fixes
tachiyomiorg/tachiyomi pull request #7166
Opened 2022-05-19 06:40 UTC by FourTOne5

Closes #7021 
Closes #5319
Fixes #6751 
Fixes #3394

2022-05-23 21:13 UTC, arkon requested changes

2022-05-23 21:13 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
> +            File(mangaDir.absolutePath, NOMEDIA_NAME).createNewFile()
You can use `DiskUtil.createNoMediaFile(...)`

2022-05-23 21:13 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
> +                .filter { it.isFile && it.nameWithoutExtension.lowercase() == "cover" }
Can uses `.equals("cover", ignoreCase = true)`

2022-05-23 21:13 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
> -                    }
Don't we still need this?

2022-05-24 03:46 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
> -                    }
The modified manga only stays in memory. Could move this in `getMangaDetails` if you want

2022-05-24 03:48 UTC, FourTOne5 commented on app/src/main/java/eu/kanade/tachiyomi/source/LocalSource.kt
> -                    }
Actually I just realized this is a different method

2022-05-24 22:02 UTC, merged