Use SQLDelight in reader to update history
tachiyomiorg/tachiyomi pull request #7185
Opened 2022-05-22 16:28 UTC by FourTOne5

Makes history screen update after reading a chapter (Related to #6951)

Also starts counting read duration of a chapter 👀

2022-05-22 16:42 UTC, saud-97 reviewed
Maybe this can potentially solve https://github.com/tachiyomiorg/tachiyomi/issues/7147 if it was possible to also calculate each page read time and if the read time is unreasonably low ignore it and use last page time.

2022-05-22 16:42 UTC, saud-97 commented on app/src/main/sqldelight/migrations/15.sqm
> +DROP VIEW IF EXISTS historyView;
Does this drop has to happen always?

2022-05-22 16:42 UTC, saud-97 commented on app/src/main/sqldelight/migrations/15.sqm
> +mangas.thumbnail_url AS thumnailUrl,
Typo in `thumnailUrl`

2022-05-22 16:49 UTC, FourTOne5 commented on app/src/main/sqldelight/migrations/15.sqm
> +DROP VIEW IF EXISTS historyView;
Only happens once under normal circumstances

2022-05-22 16:49 UTC, FourTOne5 commented on app/src/main/sqldelight/migrations/15.sqm
> +mangas.thumbnail_url AS thumnailUrl,
Copy pasted from `historyView` typo seems to be from there

2022-05-22 16:51 UTC, FourTOne5 commented
> Maybe this can potentially solve #7147 if it was possible to also calculate each page read time and if the read time is unreasonably low ignore it and use last page time.

The issues is with reader. The reader jumps few pages for some chapters when it gets closed.

2022-05-22 16:51 UTC, FourTOne5 commented
I'll

2022-05-26 06:24 UTC, ghostbear requested changes

2022-05-26 06:24 UTC, ghostbear commented on app/src/main/sqldelight/data/chapters.sq
> +WHERE _id = :chapterId;
Would be more preferable if this was an partial update like 1.x does
https://github.com/tachiyomiorg/tachiyomi-1.x/blob/dev/data/src/commonMain/sqldelight/tachiyomi/data/Chapter.sq#L33-L45
https://github.com/tachiyomiorg/tachiyomi-1.x/blob/d744b3c043eeffadb247ee48fa6aef406ef49d7f/data/src/commonMain/kotlin/manga/ChapterRepositoryImpl.kt#L116-L131
https://github.com/tachiyomiorg/tachiyomi-1.x/blob/d744b3c043eeffadb247ee48fa6aef406ef49d7f/domain/src/commonMain/kotlin/manga/model/ChapterUpdate.kt#L11-L24

2022-05-26 06:24 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +    private val chapterRepository: ChapterRepository = Injekt.get(),
Maybe have some use cases instead?

2022-05-27 00:05 UTC, arkon requested changes
It would've been more ideal if you did the SQLDelight work before adding the new timing stuff.

2022-05-27 00:05 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
> +        presenter.setReadStartTime()
Won't this fail to sum up the times if you read a chapter in multiple sessions? Or is that dependant on the math happening in the SQL update statement?

2022-05-27 00:05 UTC, arkon commented on app/src/main/sqldelight/data/chapters.sq
> +SET manga_id = coalesce(:mangaId, manga_id),
What's up with the coalescing?

2022-05-27 00:05 UTC, arkon commented on app/src/main/sqldelight/migrations/15.sqm
> +CREATE INDEX history_chapter_id_index ON history(chapter_id);
Might be better to keep the old `history_history_chapter_id_index` name just so it's easier to search for.

2022-05-27 00:05 UTC, arkon commented on app/src/main/sqldelight/migrations/15.sqm
> +    time_read INTEGER NOT NULL ,
```suggestion
    time_read INTEGER NOT NULL,
```

2022-05-27 00:05 UTC, arkon commented on app/src/main/sqldelight/migrations/15.sqm
> +CREATE TABLE history(
It'd be nice to add comments on what's changing.

2022-05-27 00:05 UTC, arkon commented on app/src/main/sqldelight/migrations/15.sqm
> +JOIN (
Can you indent the contents so it's a bit more readable?

2022-05-27 10:27 UTC, AntsyLich commented on app/src/main/java/eu/kanade/data/history/HistoryRepositoryImpl.kt
> +            try {
Tried it the first time and it gave me error
![image](https://user-images.githubusercontent.com/59261191/170678637-2239a21d-0551-4f22-9cfe-bffe7c2a8c59.png)

2022-05-27 10:27 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/chapter/model/ChapterUpdate.kt
> +    val mangaId: Long? = null,
It's made this way so we can do partial update of a chapter without knowing other values. 
In `chapters.sq` is `coalesce()` is used so that if the value here is null it will retain the current value for the chapter.

This is based on 1.x implementation
https://github.com/tachiyomiorg/tachiyomi-1.x/blob/dev/data/src/commonMain/sqldelight/tachiyomi/data/Chapter.sq#L33-L45
https://github.com/tachiyomiorg/tachiyomi-1.x/blob/d744b3c043eeffadb247ee48fa6aef406ef49d7f/data/src/commonMain/kotlin/manga/ChapterRepositoryImpl.kt#L116-L131
https://github.com/tachiyomiorg/tachiyomi-1.x/blob/d744b3c043eeffadb247ee48fa6aef406ef49d7f/domain/src/commonMain/kotlin/manga/model/ChapterUpdate.kt#L11-L24

2022-05-27 10:27 UTC, AntsyLich commented on app/src/main/sqldelight/data/chapters.sq
> +SET manga_id = coalesce(:mangaId, manga_id),
Explained in the other comment

2022-05-27 10:28 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
> +        presenter.setReadStartTime()
it's dependent on the sql statement

2022-05-27 21:06 UTC, arkon commented on app/src/main/java/eu/kanade/data/history/HistoryRepositoryImpl.kt
> +            try {
Seems to work fine for me when I added:

```
    sqldelight {
        database("history") {
            dialect = "sqlite:3.24"
        }
    }
```

To the app module's `build.gradle.kts` `android` block.

2022-05-28 03:17 UTC, AntsyLich commented on app/src/main/java/eu/kanade/data/history/HistoryRepositoryImpl.kt
> +            try {
I was putting it in the wrong place :headpalm:

2022-05-28 13:09 UTC, merged