Fix global update ignoring network constraint
tachiyomiorg/tachiyomi pull request #7188
Opened 2022-05-23 15:41 UTC by shadow578

Fixes automatic library updates ignoring network constraint and closes #7016 .

Note: I've added a constraint for unmetered network to the work request. That way, the job will run as soon as a unmetered (== wifi) connection is available instead of waiting for the next run in however many hours the user set it to.

2022-05-23 21:50 UTC, arkon requested changes

2022-05-23 21:50 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt
> +                    .setRequiredNetworkType(if (DEVICE_ONLY_ON_WIFI in restrictions) { NetworkType.UNMETERED } else { NetworkType.CONNECTED })
Metered (or unmetered) networks don't actually strictly correlate with it being Wi-Fi or not, hence the separate `isConnectedToWifi` check earlier on. You can just leave this as-is.

2022-05-24 17:01 UTC, shadow578 commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt
> +                    .setRequiredNetworkType(if (DEVICE_ONLY_ON_WIFI in restrictions) { NetworkType.UNMETERED } else { NetworkType.CONNECTED })
I'm aware that the unmetered network constraint doesn't correlate to the network being WiFi. However, as i explained in the PR text, i added this so that WorkManager will schedule the job to run only on unmetered connections (which, for most users) will be their wifi connection. 
Otherwise, the job could get started on a mobile connection, where it will then fail. This might lead to a situation where the job never runs (e.g. when the update job is scheduled for every 24h, and every time the job is scheduled the device is off of wifi).

I'm assuming that if you're going to the effort of constraining tachiyomi to only use wifi, you wouln't want it to use a metered wifi (which is a option you have to set manually) either.

2022-05-25 10:09 UTC, shadow578 commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt
> +                    .setRequiredNetworkType(if (DEVICE_ONLY_ON_WIFI in restrictions) { NetworkType.UNMETERED } else { NetworkType.CONNECTED })
I really think we should use the network constraint that workmanager offers to ensure jobs are only scheduled when they make sense. 
Perhaps i could add an additional option to settings so that users can explicitly enable the constraint in this line, instead of implicitly enabling it for them. Something along the lines of 'Only update on unmetered Networks' (in the same menu where one can set the option to only update over wifi, that is)

2022-05-25 13:24 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt
> +                    .setRequiredNetworkType(if (DEVICE_ONLY_ON_WIFI in restrictions) { NetworkType.UNMETERED } else { NetworkType.CONNECTED })
I doubt most users would really understand what that means (it isn't even clear in the developer documentation), but it may be useful for some people.

I'm not super convinced it'll really affect most job schedules since having a metered Wi-Fi connection is probably rare unless a VPN is being used as well, but go for it.

2022-05-25 16:58 UTC, shadow578 commented
Added explicit constraint, see attached screenshot
![update-constraints](https://user-images.githubusercontent.com/52449218/170319141-93165764-726f-4d6f-9e9b-50aad4e2cb44.png)

2022-05-28 02:18 UTC, arkon requested changes
Minor nitpicks but otherwise LGTM.

2022-05-28 02:18 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="network_not_metered">Only on unmetered Network</string>
```suggestion
    <string name="network_not_metered">Only on unmetered network</string>
```

2022-05-28 02:18 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt
> +import eu.kanade.tachiyomi.data.preference.*
Don't use wildcard imports.

2022-05-28 02:18 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/setting/SettingsLibraryController.kt
> +import eu.kanade.tachiyomi.data.preference.*
Same here re: wildcard imports.

2022-05-28 02:27 UTC, Saud-97 commented
> Added explicit constraint, see attached screenshot ![update-constraints](https://user-images.githubusercontent.com/52449218/170319141-93165764-726f-4d6f-9e9b-50aad4e2cb44.png)

I suggest to unify the language used and make it `While condition" or drop the while word to match the rest.

2022-05-28 13:09 UTC, merged

2022-05-28 13:11 UTC, arkon commented
I'll take care of the minor comments separately.