New: Migrating titles maintains custom covers #7189
tachiyomiorg/tachiyomi pull request #7196
Opened 2022-05-25 01:18 UTC by saud-97

Implemented Migrating titles maintains custom covers #7189

2022-05-25 20:48 UTC, saud-97 commented
I'll

2022-05-28 02:23 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="custom_covers">Custom Covers</string>
```suggestion
    <string name="custom_covers">Custom covers</string>
```

2022-05-28 02:23 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/MigrationFlags.kt
> +    val titles get() = arrayOf(R.string.chapters, R.string.categories, R.string.track, R.string.custom_covers)
It'd be ideal if the option wasn't presented if there isn't actually a custom cover. I guess the same applies for trackers too though, so maybe we can just do that as a followup.

2022-05-28 02:58 UTC, Saud-97 commented on app/src/main/res/values/strings.xml
> +    <string name="custom_covers">Custom Covers</string>
done

2022-05-28 02:58 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/MigrationFlags.kt
> +    val titles get() = arrayOf(R.string.chapters, R.string.categories, R.string.track, R.string.custom_covers)
I will try and see if I was able to do this.

2022-05-28 03:16 UTC, AntsyLich requested changes

2022-05-28 03:16 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/MigrationFlags.kt
> +    private const val CUSTOM_COVER = 0b1000
Why not `0b0101`

2022-05-28 04:10 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/MigrationFlags.kt
> +    val titles get() = arrayOf(R.string.chapters, R.string.categories, R.string.track, R.string.custom_covers)
I have done this and tested it.
I found 3 issues with how Tachiyomi handle the logic.

First issue is that tracking option will show if the manga has any track data in db that means it would show even when the manga is no longer tracked currently and even if the tracking services is not logged in.

Second issue is that old logic depends on index on saving flags enabled status rather than flag value like 0b0001. That would cause incorrect enabled status when indices change.

```
                    // Save current settings for the next time
                    val selectedIndices = mutableListOf<Int>()
                    selected.forEachIndexed { i, b -> if (b) selectedIndices.add(i) }
```

2022-05-28 04:12 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/MigrationFlags.kt
> +    private const val CUSTOM_COVER = 0b1000
> Why not `0b0101`

That would make `CHAPTERS` and `TRACK` be mistakenly counted as enabled because that's how flags work iirc :)

2022-06-04 16:52 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/MigrationFlags.kt
> +    val titles get() = arrayOf(R.string.chapters, R.string.categories, R.string.track, R.string.custom_covers)
> First issue is that tracking option will show if the manga has any track data in db that means it would show even when the manga is no longer tracked currently and even if the tracking services is not logged in.

That's technically fine. We end up backing up/restoring that sort of data anyway, and it typically works if you just re-login.

2022-06-04 16:52 UTC, merged

2022-06-04 19:47 UTC, Kediny commented
Thank you very much!! 😁