Improved Extensions Language filtering
tachiyomiorg/tachiyomi pull request #7200
Opened 2022-05-26 08:25 UTC by saud-97

I noticed that when looking for a language during Extensions search with only selecting a specific language.
The current behavior will show extensions that are ONLY in the selected language and it will not show any extensions exist in ALL although they have the selected language internally. 

Since this behavior is misleading I created this PR to fix the behavior.

For example when selecting HANS only and disabling ALL filter this is what will show. Instead of showing only the last extension.

![image](https://user-images.githubusercontent.com/39028181/170448964-5431e053-d4e1-44c2-8e37-1422bcb554e6.png)

2022-05-26 12:49 UTC, arkon commented
I don't understand what you're searching?

2022-05-26 13:10 UTC, saud-97 commented
Let me explain a bit, currently what someone has ALL language disabled, extensions that are in ALL will not show as available for install, even if they contain the languages the user is looking for.

Before when someone intends to install an extension with the following filters
HANS = ON and ALL = OFF

Before the PR it will show

-HANS
--BILBILI MANGA

After the PR it will show

-ALL
--Bato.to
--and others that match user filtered languages

-HANS
--BILBILI MANGA

2022-05-26 23:46 UTC, arkon commented
It might make more sense to stop showing a separate "All" section for extensions and instead duplicate it in the different language sections based on the sources' languages. In parallel, wording it as something like "Multiple" would better indicate that it supports multiple languages.

2022-05-27 00:03 UTC, saud-97 commented
I planned to do show duplicated in each language but unfortunately I didn't know how to modify the groupBy to do it. since I will need to do a loop ` it.sources.forEach { it.lang }` and combine the loop with groupBy somehow overlapping.
 https://github.com/tachiyomiorg/tachiyomi/blob/9f42306f79b9faa601016e1b826acd9f575ec976/app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt#L91-L100

I tried to think how I can do it maybe in multiple steps and then combine the overlapping maps but I don't really know how to exactly do it so I left it to your discretion.

Also I agree the naming of ALL should be changed to Multilanguage or similar meaningful names.

2022-05-27 00:03 UTC, saud-97 commented
I will try and see if I can do the overlapping maps again.

2022-05-27 01:08 UTC, saud-97 commented
Well I spent sometime trying to find a solution but I wasn't able to. I thought about making the` available<Extensions.Available>` to be flattened, i.e., move the internal extensions and make it 1 level list. But I wasn't able to change the list type from `AvailableExtensionSources `to `Extensions.Available` to make it work in the code.

If someone want to understand more on how the extensions json and sources mapping were made have a look at https://raw.githubusercontent.com/tachiyomiorg/tachiyomi-extensions/repo/index.json

2022-05-28 13:01 UTC, arkon commented
Closing this since the PR as-is isn't useful. Feel free to log the ideas/findings in an issue.

2022-05-28 20:44 UTC, Saud-97 commented
Can someone re-open this PR. I was able to define the logic for correctly showing sources under their own language instead of putting them under ALL. After the last changes the PR should be ready for review again.

2022-05-28 22:18 UTC, Saud-97 commented
The only remaining thing is to refactor the app and the update the **ALL** logic or if only minimum changes are needed then just hide the ALL filter from Extensions Page to not show it explicitly and just show it inside other languages groups. These are optional changes I can think of but not required.

2022-05-28 23:25 UTC, nzoba commented on app/src/main/java/eu/kanade/tachiyomi/extension/model/Extension.kt
> +        return Extension.Available(
You could use `ext.copy(...)` to avoid setting each parameter. And maybe use `ext.pkgName + lang` instead of an index ?

2022-05-28 23:25 UTC, nzoba commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +                available.forEach { ext ->
Imo, `flatMap` is better in this case. Probably something like that :
```
  val flattenedAvailable = available.flatMap { ext ->
      ext.sources.filter { it.lang in activeLanguages }
          .map {
          if (ext.lang == it.lang) ext else it.toExtension(ext)
      }
  }
```

2022-05-29 00:33 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/extension/model/Extension.kt
> +        return Extension.Available(
Yes I will use copy, I am still getting used to kotlin so I forgot copy method.
Regarding `lang `instead of index it wouldn't work since some extensions have repeated `lang `values.

2022-05-29 00:53 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +                available.forEach { ext ->
Thanks for the suggestion.

2022-05-29 05:11 UTC, AntsyLich requested changes

2022-05-29 05:11 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +                        else ext.copy(name = it.name, lang = it.lang, pkgName = ext.pkgName + i)
```suggestion
                        else ext.copy(name = it.name, lang = it.lang, pkgName = ext.pkgName.replace(".${ext.lang}.", ".${it.lang}.")
```

2022-05-29 05:11 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +                }.toSet()
Why not a list?

2022-05-29 05:11 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +    private val preferences: PreferencesHelper by injectLazy()
Move to class constructor

2022-05-29 13:11 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +                }.toSet()
Because some extenstions have duplicated sources of the same lang 
`                        if (ext.lang == it.lang) ext
`
Like Komga and few others. Set is to dedup the repeated langs to avoid app crashes. Since  compose rows have `pkgName` as the primary ID
I could check for dups manually or let the set handle it.

2022-05-29 13:16 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +                        else ext.copy(name = it.name, lang = it.lang, pkgName = ext.pkgName + i)
What's the benefits? other than possibly having issues with deduping duplicated pkg names because `it.lang` is not always unique.

2022-05-29 13:17 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +    private val preferences: PreferencesHelper by injectLazy()
I tried initially but because I received an error I moved it. Let me check again and solve the error if possible.

2022-05-30 00:18 UTC, Saud-97 commented
I have Updated the discussed changes and the PR description now shows comparison screenshots.

2022-05-30 11:45 UTC, AntsyLich requested changes

2022-05-30 11:45 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/extension/interactor/GetExtensions.kt
> +                }.toSet()
`.distinct()`?

2022-05-30 11:45 UTC, AntsyLich commented on app/src/main/java/eu/kanade/domain/extension/interactor/GetExtensions.kt
> +                    }
```suggestion
                    val extSources = extension.sources.filter { it.lang in _activeLanguages }.sortedBy { it.name }
                    if (extSources.size == 1) {
                        listOf(extension)
                    } else {
                        extSources.map {
                            extension.copy(
                                name = if (it.lang == extension.lang) extension.name else it.name,
                                lang = it.lang,
                                pkgName = extension.pkgName + ".${it.lang}",
                            )
                        }
                    }
                    
```

2022-05-30 11:45 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +	                        }
Doesn't seem necessary?

2022-05-30 19:55 UTC, Saud-97 commented on app/src/main/java/eu/kanade/domain/extension/interactor/GetExtensions.kt
> +                }.toSet()
I read on stackoverflow a comment saying toSet() has less overhead. But since its marginal I will switch to distinct for readablity.

2022-05-30 20:09 UTC, Saud-97 commented on app/src/main/java/eu/kanade/domain/extension/interactor/GetExtensions.kt
> +                    }
I don't really see what's the point in checking the size here. If you want me to not `copy `an object if it was a primary source I can just check via `(it.lang == extension.lang)`. I removed it for readability, I guess I will put it back for performance.

2022-05-30 20:17 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsPresenter.kt
> +	                        }
Refer to discussion in #programming channel. It's needed to differentiate between partial sources and primary sources and for sorting purposes.

2022-06-06 07:41 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun enabledLanguages() = flowPrefs.getStringSet("source_languages", setOf("en", Locale.getDefault().language))
extensions like komaga, mango will be hidden then

2022-06-06 08:42 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun enabledLanguages() = flowPrefs.getStringSet("source_languages", setOf("en", Locale.getDefault().language))
Isn't "all" enabled by default to show extensions that multi languages extensions that may possibly support "en"? 

I honestly don't think most users will even be aware about Komga.
Regarding mango I can see it has a partial source "en" so it will still be shown regardless of "all" being enabled or not.

```
  {
    "name": "Tachiyomi: Mango",
    "pkg": "eu.kanade.tachiyomi.extension.all.mango",
    "apk": "tachiyomi-all.mango-v1.3.9.apk",
    "lang": "all",
    "code": 9,
    "version": "1.3.9",
    "nsfw": 0,
    "hasReadme": 0,
    "hasChangelog": 1,
    "sources": [
      {
        "name": "Mango",
        "lang": "en",
        "id": "2882993841250976719",
        "baseUrl": "",
        "versionId": 1,
        "hasCloudflare": 0
      }
    ]
  },
```

2022-06-16 15:22 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun enabledLanguages() = flowPrefs.getStringSet("source_languages", setOf("en", Locale.getDefault().language))
> Was just saying as an example. But keep it enabled

I honestly disagree.

Currently the app by default enabled All, en, and current system locale. After my change en and current system local will even show extensions that are overlapped from All. So whats the point of showing All extensions again as duplicates if they don't explicitly include the languages the user most likely would be interested in?

I have checked which extensions that only has All or other as a lang which were only 10 out of 63 extensions:
```
    "apk": "tachiyomi-all.buondua-v1.3.1.apk",
    "apk": "tachiyomi-all.everiaclub-v1.3.2.apk",
    "apk": "tachiyomi-all.foolslidecustomizable-v1.3.3.apk",
    "apk": "tachiyomi-all.hentaishark-v1.3.5.apk",
    "apk": "tachiyomi-all.junmeitu-v1.3.2.apk",
    "apk": "tachiyomi-all.kavita-v1.3.4.apk",
    "apk": "tachiyomi-all.komga-v1.3.40.apk",
    "apk": "tachiyomi-all.lanraragi-v1.3.12.apk",
    "apk": "tachiyomi-all.xinmeitulu-v1.3.3.apk",
    "apk": "tachiyomi-all.yaoimangaonline-v1.3.2.apk",
``` 

Do you still think its worth showing 63 extensions possibly duplicated x3 times (cuz of possible overlapping with other locales) to be shown as default?

2022-06-16 15:29 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun enabledLanguages() = flowPrefs.getStringSet("source_languages", setOf("en", Locale.getDefault().language))
If you still think those 10 sources should show by default. I would suggest to include en locale in these sources as part of their lang set similar to Tachidesk ext. Since en will be enabled by default this will force them to show.

```
  {
    "name": "Tachiyomi: Tachidesk",
    "pkg": "eu.kanade.tachiyomi.extension.all.tachidesk",
    "apk": "tachiyomi-all.tachidesk-v1.3.5.apk",
    "lang": "all",
    "code": 5,
    "version": "1.3.5",
    "nsfw": 1,
    "hasReadme": 0,
    "hasChangelog": 0,
    "sources": [
      {
        "name": "Tachidesk",
        "lang": "en",
        "id": "3100117499901280806",
        "baseUrl": "",
        "versionId": 1,
        "hasCloudflare": 0
      }
    ]
  },
```

2022-06-17 03:00 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun enabledLanguages() = flowPrefs.getStringSet("source_languages", setOf("en", Locale.getDefault().language))
Unlike tachidesk the others can't filter series via language so can't

2022-09-07 21:00 UTC, closed without merging