MangaUpdates tweaks
tachiyomiorg/tachiyomi pull request #7205
Opened 2022-05-27 15:01 UTC by ghostbear

- Change status to reading when user read chapter
- Use decimal point for rating (isn't a user preference from what I understand)
- Parse HTML description to text  (I asked about if the API could provide it and the MU DEV said some endpoint do allow for it to be, search endpoint doesn't, and it may become Markdown in the future)

2022-05-27 20:58 UTC, arkon requested changes

2022-05-27 20:58 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/track/mangaupdates/MangaUpdates.kt
> +        return values
```kotlin
(0..9).flatMap { i -> (0..9).map { j -> "$i.$j" } } + listOf("10.0")
```

Should also pull this out so it doesn't need to get recreated every time.

2022-05-28 20:59 UTC, Saud-97 commented
Please also parse HTML of title. Consider checking if other fields need any extra parsing similarly to ensure correctness.

![image](https://user-images.githubusercontent.com/39028181/170842675-9b7cb282-43f7-49c2-9503-c2a1c25bce71.png)

2022-05-28 21:02 UTC, Saud-97 requested changes

2022-05-28 21:02 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/data/track/mangaupdates/dto/Record.kt
>          title = this@toTrackSearch.title ?: ""
```suggestion
        title = Jsoup.parse(this@toTrackSearch.title ?: "").text()
```

2022-05-28 22:36 UTC, merged