Download ahead after reading
tachiyomiorg/tachiyomi pull request #7226
Opened 2022-05-29 14:31 UTC by nzoba

I already added it to J2K (cf. [PR](https://github.com/Jays2Kings/tachiyomiJ2K/pull/1174)). At first it was **while** reading but after discussing it with Jay we decided to only download **after** reading to avoid potential double traffic (downloading + fetching a chapter)

| Download settings | Download ahead |
| ------- | ------- |
|![Screenshot_1653833779](https://user-images.githubusercontent.com/55888232/170873969-7fb6d423-c6ea-4062-8af9-5a40b690e681.png) | ![Screenshot_1653834092](https://user-images.githubusercontent.com/55888232/170874016-86e601f6-b1cb-49d9-9f3a-fe85142064b5.png) |

2022-05-29 14:55 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +            if (totalPages != 0 && (currentChapter.chapter.last_page_read + 1.0) / totalPages > 0.33 || isAnyPrevChapterDownloaded) {
I don't see the need to check current progress to be at least 33% to queue the next chapters download. Keeping the second condition only will be better imo. Keeping the 33% condition will be meaningful if the feature is download "ahead" during reading.

2022-05-29 14:58 UTC, Saud-97 commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +        if (chaptersNumberToDownload == 0 || !manga.favorite) return
Is the second condition `!manga.favorite` needed?

2022-05-29 15:03 UTC, Saud-97 commented on app/src/main/res/values/strings.xml
> +    <string name="download_ahead_info">Download ahead only applies to entries in library and if the last chapter read was downloaded</string>
It would be better if this was reworded to be clearer and mention that it only triggers on reader exit.

2022-05-29 15:09 UTC, Riztard commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +            if (totalPages != 0 && (currentChapter.chapter.last_page_read + 1.0) / totalPages > 0.33 || isAnyPrevChapterDownloaded) {
right, if for example we set to "2" it wont download the third one right
or is there any example case where it needed that

2022-05-29 15:10 UTC, Riztard commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +        if (chaptersNumberToDownload == 0 || !manga.favorite) return
i think so, people might just want to check something or only reading 1/few chapter if not in library

2022-05-29 15:13 UTC, Riztard commented
wait this didnt trigger at the end of chapter transition? but on reader exit?

2022-05-29 16:09 UTC, nzoba commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +        if (chaptersNumberToDownload == 0 || !manga.favorite) return
Yeah, as Riztard said
Almost the same for the current progress at 33% (random value), it's to avoid downloading in case of miss-clicking or if you just want to check something at the beginning of a chapter

2022-05-29 16:09 UTC, nzoba commented
Well yes, I know it's far from being optimal and less useful than `while reading` but it's either that or :
1. We prevent the user from going to the next chapter while it's not downloaded (= bad UX)
2. We accept a potential double traffic that may be quite bad for the sources, especially the slower ones (= bad for sources)

If you have any idea to avoid these 2 problems while downloading directly in the reader, I would happily take it

2022-05-29 17:03 UTC, Saud-97 commented
> Well yes, I know it's far from being optimal and less useful than `while reading` but it's either that or :
> 
> 1. We prevent the user from going to the next chapter while it's not downloaded (= bad UX)
> 2. We accept a potential double traffic that may be quite bad for the sources, especially the slower ones (= bad for sources)
> 
> If you have any idea to avoid these 2 problems while downloading directly in the reader, I would happily take it

So far the best possible outcome is that if we could solve the double traffic by for example download ahead the next.next chapter and implement a download kill switch when the reader catches up to the downloaded images. Of course this will also require your other PR to be implemented https://github.com/Jays2Kings/tachiyomiJ2K/pull/1176. Or if there is any other similar ways to handle the duplicate requests. 

Honestly in current status I don't really see the benefit of having the feature without it working as "during" instead of after. You are just saving the user from manually clicking the download action when he already left the reader.

2022-05-30 11:32 UTC, AntsyLich requested changes

2022-05-30 11:32 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +            .distinctBy { it.name }
Why?

2022-05-30 11:32 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +        private var isAnyPrevChapterDownloaded = false
why in companion object?

2022-05-30 11:32 UTC, AntsyLich commented on app/src/main/res/values/strings.xml
> +    <string name="download_ahead_info">Download ahead is triggered after exiting the reader, it only applies to entries in library and if the most recently read chapter was downloaded</string>
```suggestion
    <string name="download_ahead">Download ahead</string>
    <string name="auto_download_after_reading">After reading download</string>
    <plurals name="next_unread_chapters">
        <item quantity="one">Next unread chapter</item>
        <item quantity="other">Next %d unread chapters</item>
    </plurals>
    <string name="download_ahead_info">Chapters are added to download queue after exiting the reader.\nOnly works on entries in library and if the previous read chapter was downloaded</string>
```

2022-05-31 06:57 UTC, Riztard commented
> Well yes, I know it's far from being optimal and less useful than `while reading` but it's either that or :
> 
> 1. We prevent the user from going to the next chapter while it's not downloaded (= bad UX)
> 2. We accept a potential double traffic that may be quite bad for the sources, especially the slower ones (= bad for sources)
> 
> If you have any idea to avoid these 2 problems while downloading directly in the reader, I would happily take it

make it only if the next chapter is downloaded?

if need to exit the reader, people can just download the next 5/10 ch and it will be simpler right?

2022-06-01 23:47 UTC, Saud-97 commented
Yeah it looks much better now. And to mitigate the double traffic issue even more I recommend doing a check if the current chapter being loaded is also still being downloaded to pause the download for that chapter and resume it on reader exit (similar to your previous after reading commit). Since when it resumes it will just download using the cache instead of going to the source for a second time and cause extra traffic.

2022-06-02 08:14 UTC, Riztard commented
> Yeah it looks much better now. And to mitigate the double traffic issue even more I recommend doing a check if the current chapter being loaded is also still being downloaded to pause the download for that chapter and resume it on reader exit (similar to your previous after reading commit). Since when it resumes it will just download using the cache instead of going to the source for a second time and cause extra traffic.

just ignore? so it will load current chapter and download 3rd chapter

2022-06-02 13:46 UTC, vengiare commented
I feel like feature should be called `While reading automatically download`, just like `After reading automatically delete`. Current one can be confusing.

Though I don't know if the dialog also should use numbers as words (like `After reading automatically delete` dialog) or plain numbers (like `Manga screen > Download dropdown`)

2022-06-03 12:45 UTC, jferdous70 commented
> I feel like feature should be called `While reading automatically download`, just like `After reading automatically delete`. Current one can be confusing.
> 
> Though I don't know if the dialog also should use numbers as words (like `After reading automatically delete` dialog) or plain numbers (like `Manga page > Download dropdown`)

I feel your suggestion sounds much worse than OP, much more awkward. Don't think there's a reason to change this. 

In fact, _After reading automaticaly delete_ sounds bad too. Should change that instead imo

2022-06-03 12:51 UTC, vengiare commented
> "Download next unread chapters while reading" "Next 3 chapters" 

This just sounds really confusing. Whereas

> "After reading automatically delete" "Third to last read chapter"
> "While reading automatically download" "Next 3 chapters"

... makes sense to read right away.

2022-06-03 17:30 UTC, nzoba commented
I agree, `While reading automatically download` alone sounds like Yoda's talking but it makes sense if you read with the options.
Imo, `Auto download while reading` looks better but I don't really mind

Btw I added a few things :
1. When you start reading a chapter **pending but not yet downloaded**, it stops (removes) the chapter's download
2. If you exit the reader mid-chapter, the chapter is added back to the queue directly after the chapter currently being downloaded
3. If you exit at the end of the chapter or continue to the next one same as 2. Except if you have the setting `After reading auto delete` set to last chapter, in this case the chapter won't be downloaded

2022-06-03 18:25 UTC, AntsyLich commented
Supersedes #3296
Closes #3295

2022-06-04 01:33 UTC, Riztard commented
> I agree, `While reading automatically download` alone sounds like Yoda's talking but it makes sense if you read with the options. Imo, `Auto download while reading` looks better but I don't really mind
> 
> Btw I added a few things :
> 
> 1. When you start reading a chapter **pending but not yet downloaded**, it stops (removes) the chapter's download
> 2. If you exit the reader mid-chapter, the chapter is added back to the queue directly after the chapter currently being downloaded
> 3. If you exit at the end of the chapter or continue to the next one same as 2. Except if you have the setting `After reading auto delete` set to last chapter, in this case the chapter won't be downloaded

what will happen in case like this:
1. there is some failed/paused chapter(another manga/same) in the download queue. 
- will it restart while adding to queue? 
- will the chapter added going to be 1st in the list so it can start immediately? (if there is some pending download from same manga)
2. i forgot number 2 😂

2022-06-04 13:52 UTC, nzoba commented
It will restart if it vas already running or if the queue was empty. If it was paused it won't
Yes it's added at 1st position

2022-06-04 14:48 UTC, AntsyLich requested changes

2022-06-04 14:48 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +            }
```suggestion
            chapterDownload?.let {
                downloadManager.addDownloadsToStartOfQueue(listOf(it))
                it = null
            }
```

2022-06-04 14:48 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderPresenter.kt
> +        if (getCurrentChapter()?.pageLoader !is DownloadPageLoader) return
move this to top too for early exit

2022-06-04 22:16 UTC, Sazaju commented
Nice to see it going again. Thanks a lot. {^_^}b

2022-07-21 14:54 UTC, AntsyLich commented
Can extract download icon in transition view as a separate pr

2022-07-21 19:17 UTC, nzoba commented
> Can extract download icon in transition view as a separate pr

Done

2022-07-22 02:42 UTC, Riztard commented
also btw what will happen if the chapter filter is applied?
will it download 2a or 3

for example:
```
ch 1
ch 2
ch 2a (hidden by filter)
ch 3
```

2022-07-22 08:19 UTC, nzoba commented
> also btw what will happen if the chapter filter is applied? will it download 2a or 3
> 
> for example:
> 
> ```
> ch 1
> ch 2
> ch 2a (hidden by filter)
> ch 3
> ```

Only the visible chapters are automatically downloaded, the hidden chapters are ignored. In your example, 2a won't be downloaded but 3 will be

2022-07-22 08:23 UTC, AntsyLich commented
So it's like downloading next chapter from download menu at action bar

2022-07-22 08:30 UTC, nzoba commented
Exactly, same logic

2022-08-22 16:46 UTC, arynthernium commented
It's been a month, have there been any updates to this? I don't want to sound impatient, just wondering where activity is on this.

2022-08-22 17:09 UTC, nzoba commented
No idea, the feature itself is done, now it's up to the devs to decide if it needs further reviews or can be merged
They are probably quite busy rewriting the app architecture for now, so it may take a while

2022-08-22 17:22 UTC, arkon commented
I think I skimmed through it a few days ago and it seemed fine. Can you just resolve the merge conflicts?

2022-08-22 18:59 UTC, nzoba commented
> I think I skimmed through it a few days ago and it seemed fine. Can you just resolve the merge conflicts?

Done

2022-08-22 19:23 UTC, arynthernium commented
Awesome. Looks good to merge whenever the devs take a look. Thanks for this feature- it's one of the things I've looked for in tachiyomi extensively, and this makes me glad tachiyomi is open source and has the developer community surrounding it. This likely wouldn't ever be possible if it weren't community built. I look forward to seeing this in the app :)

2022-08-22 21:37 UTC, merged