Kavita tracker
tachiyomiorg/tachiyomi pull request #7488
Opened 2022-07-09 13:02 UTC by ThePromidius

This PR adds the option to enable two way tracking for Kavita.

2022-07-13 13:16 UTC, ghostbear requested changes

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    var apiUrl = ""
Move to top of the class so one can quick glance over what variables the class uses

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    private fun getToken(url: String) {
```suggestion
    }
    
    private fun getToken(url: String) {
```

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    }
Could perhaps be simplified to this
```suggestion
    var apiUrl = ""
        set(value) {
            field = "${value.split("/api/").first()}/api"
        }
```

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    private fun getApiVolumesUrl(url: String): String {
```suggestion
    }
    
    private fun getApiVolumesUrl(url: String): String {
```

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    private fun getIdFromUrl(url: String): Int {
```suggestion
    }
    
    private fun getIdFromUrl(url: String): Int {
```

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +        return "${url.split("/api/").first()}/api/Series/volumes?seriesId=${getIdFromUrl(url)}"
Why not use `apiUrl` or `getCleanedApiUrl`?
```suggestion
        return "${apiUrl}/Series/volumes?seriesId=${getIdFromUrl(url)}"
```

```suggestion
        return "${getCleanedApiUrl(url)}/Series/volumes?seriesId=${getIdFromUrl(url)}"
```

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    }
Could be moved to `SeriesDto` as a member function

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +            return returnMaxChapter
```suggestion
            return if (maxChapterNumber > volumeNumber) maxChapterNumber else volumeNumber
```

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +            }
```suggestion
            for (volume in listVolumeDto) {
                if (volume.chapters.maxOf { it.number!!.toFloat() } == 0f) {
                    volumeNumber++
                } else if (maxChapterNumber < volume.chapters.maxOf { it.number!!.toFloat() }) {
                    maxChapterNumber = volume.chapters.maxOf { it.number!!.toFloat().toInt() }
                }
            }
```

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaModels.kt
> +data class ProgressDto(
This is unused

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaModels.kt
> +data class PostUpdateChapterDto(
This is unused

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +        return url.split("/").last().toInt()
```suggestion
        return url.substringAfterLast("/").toInt()
```

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    private fun SeriesDto.toTrack(): TrackSearch = TrackSearch.create(TrackManager.KAVITA).also {
```suggestion
    }
    
    private fun SeriesDto.toTrack(): TrackSearch = TrackSearch.create(TrackManager.KAVITA).also {
```

2022-07-13 13:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    private fun getTotalChapters(url: String): Int {
```suggestion
    }
    
    private fun getTotalChapters(url: String): Int {
```

2022-07-15 22:44 UTC, ThePromidius commented
@ghostbear Thanks for the review. Didn't know you could do lot's of thing you showed me. I didn't expect to get reviewed that fast. 

I talked with the dev of Kavita. We're going to hold of this PR until all support is on stable version. We don't want to confuse people with stable build of Kavita with preview versions.

I will close this PR and will reopen it when its ready. I will keep updating it since i have to add some changes you suggested so you might be notified.

Again just for reference, this PR is to be opened when the next stable of Kavita is released.
Let me know if there's any issue.

2022-07-16 09:49 UTC, ghostbear commented
> @ghostbear Thanks for the review.

(👉ﾟヮﾟ)👉

> I talked with the dev of Kavita. We're going to hold of this PR until all support is on stable version. We don't want to confuse people with stable build of Kavita with preview versions.

For your information, the preview version of Tachiyomi is currently quite unstable as we are transitioning to Jetpack Compose. And a stable version is months away.

> I will close this PR and will reopen it when its ready. I will keep updating it since i have to add some changes you suggested so you might be notified.

You might want to leave it as a draft as we have a stale action that locks issues/PRs if your plan is to reopen this.

2022-07-18 08:37 UTC, ThePromidius commented
> For your information, the preview version of Tachiyomi is currently quite unstable as we are transitioning to Jetpack Compose. And a stable version is months away.

I actually meant kavita "test" version not tachiyomi. since there's changes to support the tracking that are not in kavita stable yet.

> You might want to leave it as a draft as we have a stale action that locks issues/PRs if your plan is to reopen this.

Then i will keep it as a draft.

2022-08-26 20:04 UTC, ThePromidius commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    }
I've taken a look at other interceptors from other trackers but idk if i would be able to pull it off the way i want.
Also notice that i get the token based on what url is provided.
I get the api key from each source from the extension then with that api key i get the token.
This way you can have all sources tracked with different kavita instances.

The other trackers just have to store a single token. Meanwhile i have to save 3.
 Would it really be worth to make the interceptor? From my opinion it'd just make it more complicated.

2022-08-27 09:35 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    }
I think an interceptor is more worth it as you can cache all 3 tokens in it

2022-08-27 10:56 UTC, majora2007 commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    }
I just want to make sure I'm understanding this interceptor. An interceptor intercepts http calls and allows to modify the request.

In our case, we need to attach the JWT token to hence authentivate. As mentioned, each source will have a unique JWT that it will generate and will last one week before needing to be reauthenticated. 

So in order to be able to utilize an interceptor, we will need to store each source's JWT and handle another flow where the JWT expires, which might happen on any API vs current where we just authenticate on load. 

Thoughs?

2022-08-27 12:32 UTC, ThePromidius commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    }
Thats probably it. I checked how shikimori handles it and i think i might do what they do but storing all 3 token  with their respective URL.

When in need to refresh token, we would take the apikey from the extension as we currently do in case the user changed the opds URL in the extension settings. 

I'm actually thinking what to do in this case, where the user changes the extensions settings to another URL, say to sync other Kavita instance. The old token would still be valid hence it'd take 7 days to call the refresh flow.

2022-09-02 16:28 UTC, ThePromidius commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +    }
Added. Feel free to review again

2022-10-29 12:18 UTC, ThePromidius commented
Just pointing out that the latest stable version of kavita which has all necessary changes was released few days ago.

2022-10-29 16:37 UTC, arkon reviewed
Just some general comments. I didn't bother checking the actual logic with the Kavita API since I can't really confirm whether it's correct or not.

2022-10-29 16:37 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +                    throw Exception("Error fetching jwd token")
jwt token?

2022-10-29 16:37 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/track/kavita/KavitaApi.kt
> +            logcat(LogPriority.WARN, e) { "exception in latest-chapter\nCould not get item\nRequest:$requestUrl" }
Don't put new lines in the logs, it'll make them harder to process/read

2022-10-29 16:37 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="tracker_kavita_warning">This tracker is only compatible with the Kavita source.</string>
It'd be better to just make a more generic string that formats the name into it, considering it's the same thing for Komga.

2022-10-29 16:47 UTC, majora2007 commented
I can confirm as the maintainer of Kavita that the logic of this code does work with Kavita. 

Really appreciate the comments and hope we get this merged in soon. Thanks.

2022-11-08 09:52 UTC, AriaMoradi commented on i18n/src/main/res/values/strings.xml
> +    <string name="tracker_kavita_warning">This tracker is only compatible with the Kavita source.</string>
Maybe you are looking for this solution? https://stackoverflow.com/a/4746136

2022-11-10 23:51 UTC, ThePromidius commented on i18n/src/main/res/values/strings.xml
> +    <string name="tracker_kavita_warning">This tracker is only compatible with the Kavita source.</string>
Commit: 0c7e01bc9318fa3f1b3b746fcc4f80d1af293d2b deals with this. Also changed komga's to use the new string. Please do review this change. It works but let me know if this is not the right way hehe 😅

2022-11-11 06:06 UTC, ghostbear commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
> +                                context.toast(context.getString(R.string.enhanced_tracking_warning, "Komga"), Toast.LENGTH_LONG)
```suggestion
                                context.toast(context.getString(R.string.enhanced_tracking_warning, context.getString(trackManager.komga.nameRes())), Toast.LENGTH_LONG)
```

2022-11-11 06:06 UTC, ghostbear commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
> +                                context.toast(context.getString(R.string.enhanced_tracking_warning, "Kavita"), Toast.LENGTH_LONG)
```suggestion
                                context.toast(context.getString(R.string.enhanced_tracking_warning, context.getString(trackManager.kavita.nameRes())), Toast.LENGTH_LONG)
```

2022-11-11 20:19 UTC, merged