Use Stable interface for Updates screen + Cleanup
tachiyomiorg/tachiyomi pull request #7627
Opened 2022-07-27 14:31 UTC by AntsyLich

Co-Authored-By: Ivan Iskandar <12537387+ivaniskandar@users.noreply.github.com>

2022-07-27 16:16 UTC, ghostbear requested changes

2022-07-27 16:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesScreen.kt
> +    // Updates Selection
Instead of using these `onUpdateSelected`, `onAllUpdatesSelected`, `onInvertSelection`, `onMultiBookmarkClicked`, `onMultiMarkAsReadClicked`, `onMultiDeleteClicked` you can use the presenter directly

2022-07-27 16:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesUiItem.kt
> +        val haptic = LocalHapticFeedback.current
`UpdatesUiItem` could be done in the item composable. 

Side note: We should probably create our own `combinedClickable`, `clickable`, etc to apply this automatically

2022-07-27 16:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesController.kt
> -            if (result == AlertDialog.BUTTON_POSITIVE) presenter.deleteChapters(items)
This dialog could be moved to Compose. You can reference the other Compose dialogs on Library, History, and Category screens

2022-07-27 16:16 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesPresenter.kt
> +                .catch { logcat(LogPriority.ERROR, it) }
You could use a event channel similar to other Compose screens to bubble up the error to the user as a toast

2022-07-27 18:02 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesState.kt
> +}
I was getting error when I tried to do it like this

2022-07-27 18:06 UTC, ghostbear commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesState.kt
> +}
Well what kind of errors did you get because I didn't see any

2022-07-28 11:12 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesState.kt
> +}
i was doing ` uiModels.filter { it is UpdatesUiModel.Item && it.item.selected}` which was giving me errors

2022-07-28 12:30 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesUiItem.kt
> +        val haptic = LocalHapticFeedback.current
>`UpdatesUiItem` could be done in the item composable.

I am confusion

2022-07-28 12:32 UTC, ghostbear commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesUiItem.kt
> +        val haptic = LocalHapticFeedback.current
The haptic can be moved into the UpdatesUiItem composable

2022-07-28 13:41 UTC, ghostbear requested changes

2022-07-28 13:41 UTC, ghostbear commented on app/src/main/java/eu/kanade/tachiyomi/ui/recent/updates/UpdatesPresenter.kt
> +    val dateFormat: DateFormat by derivedStateOf { preferences.dateFormat() }
You will also need to add the import for this

```suggestion
    val dateFormat: DateFormat by mutableStateOf(preferences.dateFormat())
```

2022-07-30 15:49 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesScreen.kt
> +    val onUpdateLibrary = {
We should ideally leave any Android-y things out of the presentation layer so they can eventually be reused for cross-platform things, but we can always clean it up later as needed.

2022-07-30 15:50 UTC, merged