Displays next unread chapter on resume button
tachiyomiorg/tachiyomi pull request #7768
Opened 2022-08-15 18:22 UTC by Re-Tails

Displays the chapter number of the next unread chapter when resuming, addresses https://github.com/tachiyomiorg/tachiyomi/issues/7572.

2022-08-15 18:37 UTC, alessandrojean commented on app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
> +    DecimalFormatSymbols().apply { decimalSeparator = '.' },
This isn't ready for i18n, there's some locales that uses `,` instead of `.` as the decimal separator.

2022-08-15 18:46 UTC, AntsyLich commented
you forgot to add the button that lets me disable this

2022-08-15 18:47 UTC, arkon commented
I'm not sure it actually makes sense to increase the amount of text in the FAB, which will be pretty bad in more verbose languages / smaller screens.

2022-08-15 18:49 UTC, Re-Tails commented
> I'm not sure it actually makes sense to increase the amount of text in the FAB, which will be pretty bad in more verbose languages / smaller screens.

An alternative is to just have the chapter number only, without the resume text. That won't look great though admittedly

2022-08-15 18:53 UTC, Re-Tails commented on app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
> +    DecimalFormatSymbols().apply { decimalSeparator = '.' },
How are we planning to handle i18n? Used this formatter from app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt

2022-08-15 19:17 UTC, stevenyomi requested changes

2022-08-15 19:17 UTC, stevenyomi commented on app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
> +                        Text(text = (stringResource(id) + " " + chapterFormatter.format(nextUnreadChapterNumber.invoke())))
Some languages like Chinese and Japanese have text both before and after the number, e.g. "第 ## 章".

You also need to handle invalid negative chapter numbers.

2022-08-16 12:52 UTC, Re-Tails commented on app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
> +                        Text(text = (stringResource(id) + " " + chapterFormatter.format(nextUnreadChapterNumber.invoke())))
So something like `<resume_start> ## <resume_end>`, yep gonna add in handling fallback for invalid chapter numbers.

2022-08-16 13:26 UTC, stevenyomi commented on app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
> +                        Text(text = (stringResource(id) + " " + chapterFormatter.format(nextUnreadChapterNumber.invoke())))
Just do `String.format("Resume ch. %s", chapterNumberString)` and let translators put the `%s` in the right place.

2022-08-16 13:35 UTC, Re-Tails commented on app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
> +                        Text(text = (stringResource(id) + " " + chapterFormatter.format(nextUnreadChapterNumber.invoke())))
Oh dang, didn't realise `%s` work for these strings as well. Thanks

2022-08-18 22:57 UTC, arkon commented
Someone on Discord suggested adopting the J2K button between the info and chapters, along with a suggestion of showing the FAB only when that button isn't visible.

We could also have a subtitle below the "x chapters" heading that tells you what's next or what you're currently on?

2022-08-22 21:35 UTC, arkon commented
Closing for now, I'm not really sold on any of the solutions so far.

2022-08-22 21:35 UTC, closed without merging