Add support to skip single chapter series on global update
tachiyomiorg/tachiyomi pull request #7902
Opened 2022-08-30 21:00 UTC by alessandrojean

This PR adds a new `isSingleChapter` field to `SManga`, which defaults to `false`. If an extension marks it as `true`, and "Skip updating titles that are single chapter" is checked at the manga update restrictions, it will be skipped.

I took the liberty to enable it by default and also force enable it with a preference migration.

Still needs to be included in a stable release (and in forks too) so it can be added to the extensions' lib.

Let me know if I should change the field to snake case (to follow `thumbnail_url`).

Closes #6539.

2022-08-30 21:50 UTC, alessandrojean commented
Tested with a fork of the extensions-lib, it's working as expected.

Important to notice, if a user have an updated extension with the field in an older version of the app, it throws an error.

2022-08-31 12:47 UTC, stevenyomi commented
How is it different from a "Completed" status?

2022-08-31 12:51 UTC, alessandrojean commented
A source could not mark the status as complete (like it being unknown) and it could still be single chapter. The change is most done thinking about hentai sources that always have single chapter entries.

Also some users tends to disable the complete restriction, so having an extra one just for this case could at least help to some users keep it on after recommendation. We could maybe make it uncheckable and always on thought.

2022-08-31 12:58 UTC, alessandrojean commented
Status could be an alternative, but I'm not very sure if "Single chapter", "One shot", or other similar descriptions would really fit into being an own status option when you compare to the other options available.

2022-08-31 13:07 UTC, stevenyomi commented
I think single chapter is only one of the many reasons to prevent auto-updating. Adding only this one as a boolean field is not "general" and might cause people to request adding other reasons. It's better to add `no_auto_updates = true` to prevent it out of any reason, or add a flag field `no_auto_updates_reason = 0b00010` to allow adding more reasons.

2022-08-31 16:03 UTC, alessandrojean commented
Updated the code to have a more generic enum now, reviews are welcome 👍🏻.

2022-08-31 20:58 UTC, arkon requested changes

2022-08-31 20:58 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/source/model/UpdateStrategy.kt
> +enum class UpdateStrategy {
Can you add a JavaDoc to this with `@since extension-lib 1.4` and also bump `LIB_VERSION_MAX` to 1.4 in `ExtensionLoader`?

2022-08-31 20:58 UTC, arkon commented on app/src/main/res/values/strings.xml
> +    <string name="skipped_reason_not_always_update">Skipped because series is not marked as always update</string>
```suggestion
    <string name="skipped_reason_not_always_update">Skipped because series does not require updates</string>
```

2022-08-31 21:16 UTC, alessandrojean commented on app/src/main/java/eu/kanade/tachiyomi/source/model/UpdateStrategy.kt
> +enum class UpdateStrategy {
Done. Does the JavaDoc also needs to be added to the extension-lib?

2022-08-31 21:18 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/source/model/UpdateStrategy.kt
> +enum class UpdateStrategy {
No, that's a bit easier to figure out based on GitHub showing tags on commits.

2022-09-01 03:14 UTC, stevenyomi commented
Isn't it easier to make the field an `Int` like `status`?

2022-09-01 03:35 UTC, alessandrojean commented
Integers could work but honestly an enum it's best as it's designed for it. Using an integer could possibly allow sources to set invalid values (as it can be done with the status field with the current implementation).

2022-09-01 04:07 UTC, stevenyomi commented
We can add a data verifier/cleaner to clamp the values from source. That's a lot more efficient than doing all those conversions of an Enum.

2022-09-01 11:04 UTC, alessandrojean commented
I'd really prefer to use a structure designed for that, as status ideally should also be one. The conversions are only done when saving and reading from the database once and they're not that time consuming as they only get the `name` while encoding and do a `valueOf` (iirc) when decoding. That can really be improved later if it's really a bad performatic issue.

2022-09-01 11:39 UTC, alessandrojean commented
On a second thought maybe it would be interesting to save it as integers in the database but still expose it as enum. A column adapter could be created to encode the enum as it's ordinal value and decoding by using the `values()[index]` of the enum, clamping it to the enum bounds when doing so.

I'm gonna change this later today.

2022-09-24 14:29 UTC, arkon reviewed
Generally looks fine, but need to fix conflicts.

2022-09-24 14:29 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/source/model/UpdateStrategy.kt
> +enum class UpdateStrategy {
I'm actually not sure if it'd be nicer to just stay consistent with the existing way we handle "enums" as int constants like status or to start introducing actual enums.

I'd be okay either way though; depends on if anyone has strong feelings about it.

2022-09-24 14:30 UTC, alessandrojean commented
Will fix the conflicts this week 👍🏻.

2022-09-24 14:32 UTC, alessandrojean commented on app/src/main/java/eu/kanade/tachiyomi/source/model/UpdateStrategy.kt
> +enum class UpdateStrategy {
The status can be easily replaced with an enum in the future by using the database enum adapter, so I think it's worth the move.

2022-09-25 00:06 UTC, alessandrojean commented
Conflicts are fixed now, and the build is still running fine, so it's ready to merge again.

2022-09-25 14:12 UTC, merged