Implement simple stats screen
tachiyomiorg/tachiyomi pull request #8068
Opened 2022-09-24 15:23 UTC by AntsyLich

![Screenshot_1664032736](https://user-images.githubusercontent.com/59261191/192105996-d998c2e9-a225-48f3-bcb5-d84749b4e1a2.png)

2022-09-24 15:46 UTC, Soitora requested changes

2022-09-24 15:46 UTC, Soitora commented on i18n/src/main/res/values/strings.xml
> +    <string name="stats_unavailable">Statistics is unavailable for empty library</string>
Wording sounds wrong

2022-09-24 15:46 UTC, Soitora commented on i18n/src/main/res/values/strings.xml
> +    <string name="label_read_chapters">Read chapter</string>
Should probably be plural

2022-09-24 15:46 UTC, Soitora commented on i18n/src/main/res/values/strings.xml
> +    <string name="label_most_used_source">Most used source</string>
Is this even in still?

2022-09-24 15:52 UTC, arkon commented on app/src/main/java/eu/kanade/core/util/DurationUtils.kt
> +fun Duration.toDurationString(fallback: String): String {
This isn't really going to work for localization.

2022-09-24 15:52 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/MoreScreen.kt
> +    onCLickStats: () -> Unit,
`Click`

2022-09-24 15:52 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/stats/SimpleStatScreen.kt
> +    VerticalFastScroller(
Don't think we really need a fast scroller for this screen.

2022-09-24 15:52 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/stats/SimpleStatScreen.kt
> +    StatsSection { modifier ->
I wonder if we can have section headings so that the item labels can be shortened. @CrepeTF thoughts?

2022-09-24 15:52 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="n_a">N/A</string>
`not_applicable`

2022-09-24 15:52 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/stats/StatsPresenter.kt
> +            if (libraryManga.isEmpty()) {
Wouldn't you still technically be able to show stats? They'd just mostly be 0s.

2022-09-24 15:52 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/stats/StatsScreenState.kt
> +        // Overview
May be worth actually breaking these down into smaller data classes?

2022-09-24 17:00 UTC, ghostbear reviewed
I still think this is a super niche feature, and not needed as people can use AniList, Kitsu or a 3rd party tool to the trackers to see their stats

2022-10-22 17:51 UTC, d-najd commented
@AntsyLich are you still working on this feature? if no is it okay to take some of your code in attempt to implement the feature myself?

*cries in barely knowing how to write compose*

2022-10-22 18:08 UTC, AntsyLich commented
> @AntsyLich are you still working on this feature? if no is it okay to take some of your code in attempt to implement the feature myself?
> 
> _cries in barely knowing how to write compose_

This PR is mostly complete I'm just being lazy and not completing it. You should work on detailed stats screen instead which is supposed to show more in-depth stats.

P.S. You should join the tachiyomi discord server

2022-10-22 18:41 UTC, d-najd commented
> This PR is mostly complete I'm just being lazy and not completing it. You should work on detailed stats screen instead which is supposed to show more in-depth stats.

sure I will, would you me to include anything specifically? 

> P.S. You should join the tachiyomi discord server

I have already joined.
P.S my discord is Deltashot#2560

2022-11-02 13:46 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/stats/StatsPresenter.kt
> +            .countNot {
Didn't want to make a new list for no reason

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/core/util/DurationUtils.kt
> +fun Duration.toDurationString(): String? {
This doesn't work for i18n.

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/core/util/ListExtensions.kt
> +    for (element in this) if (predicate(element)) --count
Does efficiency matter here? If so, you'd want to use `fastForEach` instead of using an iterator.

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/stats/SimpleStatScreen.kt
> +            val readDurationString = remember(data.totalReadDuration) {
Lift this to the top of `OverviewSection`.

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/stats/SimpleStatScreen.kt
> +fun OverviewSection(
```suggestion
private fun OverviewSection(
```

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/stats/SimpleStatScreen.kt
> +fun TitlesStats(
```suggestion
private fun TitlesStats(
```

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/stats/SimpleStatScreen.kt
> +fun ChapterStats(
```suggestion
private fun ChapterStats(
```

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/stats/SimpleStatScreen.kt
> +fun TrackerStats(
```suggestion
private fun TrackerStats(
```

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/stats/SimpleStatScreen.kt
> +                    // All other numbers are localized in english
```suggestion
                    // All other numbers are localized in English
```

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/stats/SimpleStatScreen.kt
> +            val meanScoreStr = remember(data.trackedTitleCount, data.meanScore) {
Lift these

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/stats/components/StatsSection.kt
> +        shape = RoundedCornerShape(25),
Should probably just use one of the `MaterialTheme.shapes` values for consistency elsewhere?

2022-11-08 03:44 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/stats/StatsController.kt
> +    override fun createPresenter() = StatsPresenter()
Should just go full Voyager at this point.

2022-11-08 03:44 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="label_started_titles">Started</string>
Some of these strings are definitely repeated. Should try to avoid adding dupes.

2022-11-26 14:39 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="label_downloaded_chapters">Downloaded</string>
Same as `label_downloaded`?

2022-11-26 14:39 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="minute_short">%dmin</string>
Why isn't this just `m`?

2022-11-26 14:39 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/stats/StatsScreen.kt
> +        LaunchedEffect(Unit) {
Is this necessary? I thought pushing `StatsController` with the Conductor router would've taken care of that.

2022-11-26 14:52 UTC, AntsyLich commented on i18n/src/main/res/values/strings.xml
> +    <string name="minute_short">%dmin</string>
`m` is the abbreviation of meter and `min` is of minutes

2022-11-26 15:00 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="minute_short">%dmin</string>
What? It's totally contextual.

2022-11-26 15:02 UTC, AntsyLich commented on i18n/src/main/res/values/strings.xml
> +    <string name="minute_short">%dmin</string>
I'll change it to m then

2022-11-26 20:50 UTC, merged