Add ability to open random manga
tachiyomiorg/tachiyomi pull request #8232
Opened 2022-10-18 08:39 UTC by zbue

This is an attempt to add ability to open random manga in library.

Draft because I still haven't resolved other things like EFAB shrinking on scroll to work in library screen. Any help or feedback would be appreciated 🙂

2022-10-18 10:14 UTC, AntsyLich commented
Add the option to disable it

2022-10-18 10:19 UTC, THElegend5 commented
Probably have an option to only open downloaded chapter if there isn't already an option for it.

2022-10-18 10:22 UTC, THElegend5 commented
Also maybe have an option to open random for that particular category? As per category makes more sense on large libraries rather than opening a random from the whole library.

2022-10-18 10:42 UTC, jferdous70 commented
Also, please turn it off by default if it's not already

2022-10-18 10:45 UTC, stevenyomi commented
You should not make it a FAB since it's not a primary action.

Probably put it into the overflow menu, together with the global update button.

2022-10-18 14:39 UTC, jferdous70 commented
it also closes #1248

2022-10-18 16:37 UTC, zbue commented
> Add the option to disable it

@AntsyLich Once I resolve all the things in this PR. 🙂

> Probably have an option to only open downloaded chapter if there isn't already an option for it.

@THElegend5 FYI, it works with filter and/or search in library 🙂

> Also maybe have an option to open random for that particular category? As per category makes more sense on large libraries rather than opening a random from the whole library.

This implementation already opens a random manga that is in library and only from current active category.
> You should not make it a FAB since it's not a primary action.

@stevenyomi See https://github.com/tachiyomiorg/tachiyomi/issues/1248#issuecomment-800747877

2022-10-20 19:30 UTC, pikatwinky commented
@zbue You are God, thanks for this PR. I think this is such an important feature which has been missing for years

2022-10-23 04:56 UTC, zbue commented
> I'm okay with it just being in the overflow menu, which would also remove the need for a setting for it.

Done.
Btw, user search query (e.g. searching genre) + opening random manga won't be possible.

2022-10-23 05:06 UTC, zbue commented
> User search query (e.g. searching genre) + opening random manga won't be possible.

Perhaps after the app has the option to group by tags, etc., like its forks, this case will be resolved.

2022-10-23 05:16 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/library/components/LibraryToolbar.kt
> +                val (moreExpanded, onMoreExpanded) = remember { mutableStateOf(false) }
Use `by` instead of `=` that way you'll get a mutable value instead of an immutable value and a function

2022-10-23 05:16 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
> +        val getMangaForCategory = presenter.getMangaForCategory(page = presenter.activeCategory)
Move this inside the lambda block

2022-10-23 05:16 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
> +                    openManga(item)
```suggestion
                    openManga(items.random())
```
And remove the val

2022-10-23 05:16 UTC, AntsyLich commented on i18n/src/main/res/values/strings.xml
> +    <string name="information_nothing_in_here">Nothing in here</string>
```suggestion
    <string name="information_failed_to_open_random_manga">Couldn\'t open a random title</string>
```

2022-10-23 05:16 UTC, AntsyLich commented on i18n/src/main/res/values/strings.xml
> +    <string name="action_open_random_manga">Open random manga</string>
Though internally we specify everything as "manga" on the UI side we mention them as "titles".
```suggestion
    <string name="action_open_random_manga">Open random title</string>
```

2022-10-23 06:21 UTC, zbue commented on app/src/main/java/eu/kanade/presentation/library/components/LibraryToolbar.kt
> +                val (moreExpanded, onMoreExpanded) = remember { mutableStateOf(false) }
I am getting `Initializer required for destructuring declaration` here after applying what you suggested

2022-10-23 06:22 UTC, zbue commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryController.kt
> +        val getMangaForCategory = presenter.getMangaForCategory(page = presenter.activeCategory)
`@Composable invocations can only happen from the context of a @Composable function` if this is inside lambda block

2022-10-23 06:26 UTC, zbue commented on i18n/src/main/res/values/strings.xml
> +    <string name="information_nothing_in_here">Nothing in here</string>
`Nothing in here` indicates that the current category is empty, which is better I you ask me, rather than giving the user a more general message

2022-10-23 11:40 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/library/components/LibraryToolbar.kt
> +                    expanded = moreExpanded,
```suggestion
                val expanded by remember { mutableStateOf(false) }
                IconButton(onClick = { expanded = !expanded }) {
                    Icon(
                        imageVector = Icons.Default.MoreVert,
                        contentDescription = stringResource(R.string.abc_action_menu_overflow_description),
                    )
                }
                val onDismissRequest = { expanded = false }
                DropdownMenu(
                    expanded = expanded,
```

2022-10-28 22:51 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/library/components/LibraryToolbar.kt
> +                val (moreExpanded, onMoreExpanded) = remember { mutableStateOf(false) }
You'd get rid of the destructuring so that it's

```
var moreExpanded by remember { ... }
```

2022-10-30 03:10 UTC, arkon requested changes

2022-10-30 03:10 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="action_open_random_title">Open random title</string>
I actually recently reworded things like "manga" to "entry" so let's go with that instead of "title".

2022-10-30 03:10 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="information_nothing_in_here">Nothing in here</string>
Can we make it a bit more specific so it's "No entries found in this category"?

2022-10-30 14:57 UTC, merged