Add different download options within the Library
tachiyomiorg/tachiyomi pull request #8267
Opened 2022-10-22 03:44 UTC by SleepySwords

Closes: #8184

Currently, the implementation of the custom download grabs the max unread count from all selected chapters and sets that as the max. Perhaps the minimum unread count should be used?

### Images
| Custom download dialogue | Tablet view of option | Phone view of options |
| ------- | ------- | ------- |
| ![](https://user-images.githubusercontent.com/33922797/197316432-345f3979-ea00-49be-a3e1-c95d866b620c.png) | ![](https://user-images.githubusercontent.com/33922797/197316465-6c6cb71b-636c-4adb-8b1f-b1581f0cabd1.png) | ![](https://user-images.githubusercontent.com/33922797/197316588-970ebf62-71a0-446d-837d-d09fe1ac203b.png)

2022-10-22 04:54 UTC, AntsyLich commented
Remove "All" option from Library view

It should be ok if custom grabs the max value

2022-10-22 05:06 UTC, SleepySwords commented
Just out of curiosity, why should the "All" option be removed?

2022-10-22 05:19 UTC, jferdous70 commented
> Just out of curiosity, why should the "All" option be removed?

Potentially avoiding DDoSing the servers

2022-10-22 05:35 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/components/MangaBottomActionMenu.kt
> +                        val (downloadExpanded, onDownloadExpanded) = remember { mutableStateOf(false) }
Use `by` instead of `=` that way you'll get a mutable value instead of an immutable value and a function

2022-10-22 05:35 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
>          presenterScope.launchNonCancellable {
`includeRead` is redundant

2022-10-22 05:35 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
> +    fun downloadAllChapters(mangas: List<Manga>, includeRead: Boolean = false) {
This function doesn't seem to be used

2022-10-22 05:44 UTC, SleepySwords commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
> +    fun downloadAllChapters(mangas: List<Manga>, includeRead: Boolean = false) {
It's used to download unread chapters

2022-10-22 06:58 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
> +    fun downloadAllChapters(mangas: List<Manga>, includeRead: Boolean = false) {
Make the other option take amount as nullable and include all unread when it's null and remove this function

2022-10-22 07:15 UTC, SleepySwords commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
> +    fun downloadAllChapters(mangas: List<Manga>, includeRead: Boolean = false) {
oki

2022-10-27 11:47 UTC, AntsyLich requested changes

2022-10-27 11:47 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/components/MangaBottomActionMenu.kt
> +                        DownloadDropdownMenu(downloadExpanded, onDismissRequest, onDownloadClicked, includeDownloadAllOption = false)
```suggestion
                        DownloadDropdownMenu(
                            expanded = downloadExpanded,
                            onDismissRequest = onDismissRequest,
                            onDownloadClicked = onDownloadClicked,
                            includeDownloadAllOption = false,
                        )
```

2022-10-27 11:47 UTC, AntsyLich commented on app/src/main/java/eu/kanade/presentation/manga/components/MangaToolbar.kt
> +                            DownloadDropdownMenu(downloadExpanded, onDismissRequest, onClickDownload)
```suggestion
                            DownloadDropdownMenu(
                                expanded = downloadExpanded,
                                onDismissRequest = onDismissRequest,
                                onDownloadClicked = onDownloadClicked,
                            )
```

2022-10-27 11:47 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
> +
```suggestion
    fun shouldDownloadChapter(manga: Manga, chapter: Chapter): Boolean {
        val activeDownload = downloadManager.queue.find { chapter.id == it.chapter.id }
        val downloaded = downloadManager.isChapterDownloaded(chapter.name, chapter.scanlator, manga.title, manga.source)
        val state = when {
            activeDownload != null -> activeDownload.status
            downloaded -> Download.State.DOWNLOADED
            else -> Download.State.NOT_DOWNLOADED
        }
        return state == Download.State.NOT_DOWNLOADED
    }

    suspend fun getNotDownloadedUnreadChapters(manga: Manga): List<Chapter> {
        return getChapterByMangaId.await(manga.id)
            .filter { chapter ->
                !chapter.read && shouldDownloadChapter(manga, chapter)
            }
            .sortedWith(getChapterSort(manga, sortDescending = false))
    }
```

2022-10-31 02:27 UTC, merged