Few UI changes
tachiyomiorg/tachiyomi pull request #8299
Opened 2022-10-27 21:35 UTC by Dexroneum

Changes that I could do:
- Added FastScroll to History tab
- Added bottomPaddingValues to make some space between toolbars and FastScroll
- Changed VerticalFastScroller from Updates tab to FastScroll because when you put bottomContentPadding the program calculates bad and make huge space between toolbar and VerticalFastScroller 
- Formatting some code
- Changes to Sources and Extensions tabs scrollers

Changes that I couldnt do:
- MangaScreen because if I change to FastScroll this one start to have weird behavior oriented to header of activity

2022-10-28 17:22 UTC, Dexroneum commented
@arkon can you review if all is correct?

2022-10-28 20:25 UTC, arkon requested changes

2022-10-28 20:25 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesScreen.kt
> +@Composable fun UpdateScreen(
Keep the annotation on a separate line.

2022-10-28 20:25 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +            FastScrollLazyColumn(
It's relatively rare for an extension to have enough languages for this to be needed, I'd just keep it as a normal scrollbar.

2022-10-28 20:25 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> -        Divider()
I prefer having the divider between the header and the languages.

2022-10-28 20:25 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +                Switch(checked = source.enabled, onCheckedChange = null, modifier = modifier.padding(end = 8.dp))
Why?

2022-10-28 20:25 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/SourcesScreen.kt
> +    FastScrollLazyColumn(
Users really shouldn't be having so many sources that this is necessary. I'd keep it as a regular scrollbar.

2022-10-28 20:25 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/util/Constants.kt
> +val bottomPaddingValues = PaddingValues(bottom = vertical)
I really don't think this is necessary? I don't really see a benefit, and I suspect we'd forget to apply it consistently to every screen.

2022-10-28 20:25 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesUiItem.kt
> +                    fontSize = 14.sp,
Keep it small.

2022-10-28 20:59 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesScreen.kt
> +@Composable fun UpdateScreen(
👍

2022-10-28 21:01 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +            FastScrollLazyColumn(
👍

2022-10-28 21:07 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> -        Divider()
👍

2022-10-28 21:08 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/SourcesScreen.kt
> +    FastScrollLazyColumn(
👍

2022-10-28 21:09 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesUiItem.kt
> +                    fontSize = 14.sp,
as he was?

2022-10-28 21:27 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +                Switch(checked = source.enabled, onCheckedChange = null, modifier = modifier.padding(end = 8.dp))
To make some space between Scroller and Switch. I don't know how its looks on larger devices but I'm having POCO X3 Pro with 392 dpi and it's looks like this:
 
![test](https://user-images.githubusercontent.com/46288465/198734770-33ed7670-8866-43c2-a73a-7e849f835e24.jpg)

Doesn't look good right? Same goes to MangaScreen VerticalFastScroller:

![image](https://user-images.githubusercontent.com/46288465/198735218-f352ba8a-573c-4f70-8b33-ababceefaac7.png)

That's why I added some padding to the end

2022-10-28 21:29 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/util/Constants.kt
> +val bottomPaddingValues = PaddingValues(bottom = vertical)
True, but I added this const for not adding in the code too much variables that you gonna use once-twice?

2022-10-28 22:09 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +                Switch(checked = source.enabled, onCheckedChange = null, modifier = modifier.padding(end = 8.dp))
@arkon When you can please. Thank you for your time

2022-10-28 22:42 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +                Switch(checked = source.enabled, onCheckedChange = null, modifier = modifier.padding(end = 8.dp))
We don't compensate for the fastscroll anywhere, so don't do it here either. It doesn't show up when you're not scrolling anyway.

2022-10-28 22:43 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/util/Constants.kt
> +val bottomPaddingValues = PaddingValues(bottom = vertical)
I meant the concept of adding extra bottom padding in general.

2022-10-28 22:43 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesUiItem.kt
> +                    fontSize = 14.sp,
Yes.

2022-10-28 23:23 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/util/Constants.kt
> +val bottomPaddingValues = PaddingValues(bottom = vertical)
Ah, it was to make some space between toolbar and the Scroller the same bottomContentPadding that has VerticalFastScroller

2022-10-28 23:23 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesUiItem.kt
> +                    fontSize = 14.sp,
👌

2022-10-28 23:38 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +                Switch(checked = source.enabled, onCheckedChange = null, modifier = modifier.padding(end = 8.dp))
Sad to hear that, but well, I'm not a developer 😁. As I noticed by years of using this app, that the Scroller wasn't the last pain in the ass you fixed during years of development

2022-10-29 00:14 UTC, Dexroneum commented
@arkon I will make this pr as a draft again, because I noticed some weird spacing with FastScrollLazyColumn

2022-10-29 20:29 UTC, arkon commented
Superseded by 26b46cace

2022-10-29 20:29 UTC, closed without merging

2022-10-30 02:16 UTC, arkon reviewed
Leaving some comments to address https://github.com/tachiyomiorg/tachiyomi/commit/26b46cace02d3a39c0ae4dfa4e1ffad97549de00#commitcomment-88298238:

> @arkon hmm, some changes as I understand you don't liked. Can you explain why?

2022-10-30 02:16 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +                bottom = 8.dp,
The header has larger vertical paddings since it takes up more room visually.

2022-10-30 02:16 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +            text = primaryText + if (onClick != null) " ⓘ" else "",
Not really sure why this was changed, it seemed fine before.

2022-10-30 02:16 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionsScreen.kt
> +import eu.kanade.tachiyomi.R.*
We disallow wildcard imports. I'm not sure why you'd want to do it for `R` especially.

2022-10-30 02:16 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionsScreen.kt
> +                    is Header -> "header"
A lot of subclasses are similarly named, this doesn't make the code more readable.

2022-10-30 02:16 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/SourcesFilterScreen.kt
> -        modifier = modifier,
I'm not sure why you removed these.

2022-10-30 02:16 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/browse/SourcesScreen.kt
> -        contentPadding = contentPadding + topPaddingValues,
These are necessary to have consistent visual padding around the top headers.

2022-10-30 02:16 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/manga/components/ChapterHeader.kt
> +        Icon(
This doesn't seem necessary. The "real" entrypoint is in the toolbar, the action here is just a nice-to-have.

2022-10-30 08:24 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/manga/components/ChapterHeader.kt
> +        Icon(
Ah, that's why you removed the icon that was before there. Right now it make sense thanks

2022-10-30 08:26 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/SourcesScreen.kt
> -        contentPadding = contentPadding + topPaddingValues,
That's why I added bottomPaddingValues to make same functionality but to bottom toolbars

2022-10-30 08:30 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/SourcesFilterScreen.kt
> -        modifier = modifier,
As I noticed its work same without it, so I removed

2022-10-30 08:34 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionsScreen.kt
> +                    is Header -> "header"
When I changed to FastScrollLazyColumn the code started to have weird behavior, so SonarLint that I have installed was showing errors that code is duplicated, so I take action

2022-10-30 08:48 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +            text = primaryText + if (onClick != null) " ⓘ" else "",
Ah, it was because of the translations sizes. I'm sure you know that I'm an Russian translator and our language have long words and this affects some of UI like this: 

![image](https://user-images.githubusercontent.com/46288465/198870064-f9280b26-333f-40fc-bc10-1e3be24b248c.png)

So I don't know if you can fixed. @arkon

2022-10-30 08:49 UTC, Dexroneum commented on app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
> +                bottom = 8.dp,
Okay I understand 👍