Allow partially read chapters to be marked as unread in updates screen
tachiyomiorg/tachiyomi pull request #8884
Opened 2023-01-10 16:35 UTC by zbue

2023-01-11 03:28 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/updates/UpdatesScreenModel.kt
> +                        )
This should be happening in the composable, not the screen model.

2023-01-11 04:53 UTC, zbue commented on app/src/main/java/eu/kanade/tachiyomi/ui/updates/UpdatesScreenModel.kt
> +                        )
Should I do it for manga screen as well?

2023-01-11 18:42 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/updates/UpdatesScreenModel.kt
> +                        )
Sure, but I don't mind having that change seperate

2023-01-12 22:48 UTC, arkon requested changes

2023-01-12 22:48 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/updates/UpdatesUiItem.kt
> +                            context.getString(
Can just use `stringResource` in composables.

2023-01-12 22:48 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
> +                readProgressString = chapter.lastPageRead
Set the number and do the string part in the composable.

2023-01-14 23:26 UTC, merged