Added missing chapters count in MangaInfoHeader
tachiyomiorg/tachiyomi pull request #9184
Opened 2023-03-08 22:58 UTC by foxscore

# Summary
Added a “⚠️ Missing X chapters” label to the manga info header. Will not be shown if there are none missing *(duh)*.
Additionally, a “? Might be missing chapters” message will appear if the source doesn't assign chapters properly.

# Why tho?
Because nobody wants to start reading a manga, only to find out after a few hours that half the chapters are just not there.
This way, the reader might be inclined to look up the manga from a different source beforehand.

# Images
<details>
  <summary>Example: Missing 260 chapters</summary>
  
![Example_MissingChapters](https://user-images.githubusercontent.com/30923667/223869404-66b2ad51-bbd9-4242-ae70-f579c55f60ac.png)
	
</details>

<details>
	<summary>Example: Might be missing chapters</summary>
	
![Example_MightBeMissingChapters](https://user-images.githubusercontent.com/30923667/223869415-1dcd5e0d-ee09-42eb-812e-8a68771b1df0.png)

</details>

2023-03-17 02:26 UTC, arkon requested changes

2023-03-17 02:26 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
> +import eu.kanade.tachiyomi.util.getMissingChapters as getMissingChapters
Unnecessary alias?

2023-03-17 02:26 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +public fun getMissingChapters(chaptersInput: List<ChapterItem>): List<Int>? {
Could just return an `Int`, we never use the actual items.

2023-03-17 02:26 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +        if (currentChapter == -1f) {
Could probably just filter out everything without a recognized chapter number first.

2023-03-17 02:26 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt
> +        if (missingChapters == null) {
It'd probably make more sense to put this as a subtitle in `ChapterHeader`.

2023-03-17 13:06 UTC, foxscore commented on app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
> +import eu.kanade.tachiyomi.util.getMissingChapters as getMissingChapters
Was added automatically by IDE 🤷‍♂️ No idea why it did that

2023-03-17 13:16 UTC, foxscore commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +public fun getMissingChapters(chaptersInput: List<ChapterItem>): List<Int>? {
Solved in 9cf5454b1d33720d517ecda37a8ad1207ec314e5

2023-03-17 13:17 UTC, foxscore commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +        if (currentChapter == -1f) {
Solved in 9cf5454b1d33720d517ecda37a8ad1207ec314e5

2023-03-17 13:25 UTC, foxscore commented on app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt
> +        if (missingChapters == null) {
— Solved in 4637c241f0ad502d1d2b25c0613e4f3d68bae25b —
I also changed the style so that it fits better with the new location.

2023-03-18 13:51 UTC, arkon requested changes

2023-03-18 13:51 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +package eu.kanade.tachiyomi.util
Put this in the `domain` module under `tachiyomi.domain.chapter.service`. It'd be ideal to have tests too.

2023-03-18 13:51 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +public fun countMissingChapters(chaptersInput: List<ChapterItem>): Int? {
`public` is redundant on Kotlin.

2023-03-18 13:51 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +    // If any chapters[i].chapter.chapterNumber is -1, return null
I'd probably just filter out the `-1`s and continue with the rest of it in cases that you have a list like `[-1, -1, 1, 2, 3, 4, 5, ...]`.

2023-03-18 13:51 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +    val chapters = chaptersInput.sortedBy { it.chapter.chapterNumber }.reversed()
Doing it in reverse seems kind of unnecessary?

2023-03-18 13:51 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +        // The chapter number might be, for example, 16.5, (with 16 being the previous one)
When you do the initial sorting, you can also convert them to `Int`s and `distinct` the list to skip this sort of check.

2023-03-18 13:51 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/manga/components/ChapterHeader.kt
> +@Composable
I'm not sure I'm really a fan of this UI, but I guess we can iterate on it separately based on feedback.

2023-03-18 14:04 UTC, foxscore commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +    // If any chapters[i].chapter.chapterNumber is -1, return null
Should there be a check for `if all are -1`, or should these *(likely very rare)* cases be ignored?

2023-03-18 14:06 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/util/MangaMissingChapters.kt
> +    // If any chapters[i].chapter.chapterNumber is -1, return null
It'd sort of end up depend on how the check after works, but it's also not uncommon for that to happen (even if just basic cases like a single `[-1]` for a doujin). That shouldn't be considered as missing things though.

2023-03-18 17:12 UTC, foxscore commented on app/src/main/java/eu/kanade/presentation/manga/components/ChapterHeader.kt
> +@Composable
I mainly chose it because it stands out enough to catch the users attention, but I don't like that it makes the whole row take up more empty space on the top & bottom

2023-03-25 02:10 UTC, arkon approved these changes

2023-03-25 02:44 UTC, merged