change the directory's name when the chapter's name is only composed of numbers or is blank
tachiyomiorg/tachiyomi pull request #9220
Opened 2023-03-16 22:00 UTC by Hipp0x

**Issue : ** #8810 : Chapter renamed by number, blank or (invalid)

**Summary : **
I changed the directory name when we download a manga which chapters name only composed of numbers or spaces.
It will appear like "Chapter 5" instead of "5" in the download directory.

2023-04-14 08:31 UTC, Hipp0x commented
Can someone review my PR ?

2023-04-15 02:23 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
> +                newChapterName = "${R.string.chapter} $chapterName"
`R.string.chapter` resolves to some number, not the string. You'd need to do `context.getString(R.string.chapter)`.

That said, there's no point in localizing this, it'd break downloads if you switched the app language of the translation changes for some reason.

2023-04-15 02:23 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
> +            val chapterToInt = Integer.parseInt(chapterName)
There's a `String.toIntOrNull()` function that'd be useful in these kind of scenarios.

However, I don't think this is useful to do. If the chapter name is already just a number, then the downloaded chapter would already be fine?

2023-04-15 15:38 UTC, Hipp0x commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
> +            val chapterToInt = Integer.parseInt(chapterName)
should we just close the issue and this PR if it's not useful?

2023-04-15 15:42 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
> +            val chapterToInt = Integer.parseInt(chapterName)
The blank name is still applicable.

2023-04-18 17:23 UTC, Hipp0x commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
> +                newChapterName = "${R.string.chapter} $chapterName"
Do you think it's okay if I set a default value like "Chapter", or should I just find another way ?

2023-04-19 03:16 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
> +                newChapterName = "${R.string.chapter} $chapterName"
That's fine.

2023-04-21 10:10 UTC, Hipp0x commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
> +                newChapterName = "${R.string.chapter} $chapterName"
I've update the code

2023-04-22 14:36 UTC, arkon requested changes

2023-04-22 14:36 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
> +        return if (chapterName.isEmpty() || chapterName.isBlank()) {
`isBlank` is a superset of `isEmpty`

2023-04-22 14:36 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="chapter">Chapter</string>
Remove this.

2023-04-22 14:36 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt
> +    private fun getNewChapterName(chapterName: String): String {
`sanitizeChapterName` maybe

2023-04-22 15:11 UTC, arkon commented
I'll merge this on the basis that it's a _little_ bit better. It'll only realistically handle the case where there's _one_ chapter that's affected since you'll end up with conflicting names if there's multiple chapters that end up with a blank name normally.

Realistically, that should be fixed "properly" at the source/extension level.

Otherwise, the better solution would be #9238.

2023-04-22 15:11 UTC, merged