Add interval data layer
tachiyomiorg/tachiyomi pull request #9398
Opened 2023-04-26 10:18 UTC by quangkieu

2023-04-26 12:34 UTC, AntsyLich requested changes

2023-04-26 12:34 UTC, AntsyLich commented on data/src/main/sqldelight/tachiyomi/migrations/24.sqm
> +ALTER TABLE mangas ADD COLUMN calculate_interval INTEGER DEFAULT 0 NOT NULL;
Add a new line here

2023-04-26 12:34 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupManager.kt
> +                calculateInterval = 0L,
```suggestion
                nextUpdate = null,
                calculateInterval = null,
```
So it doesn't overwrite db value

2023-04-26 13:19 UTC, arkon reviewed
Make sure to bump up the `versionCode` in `app/build.gradle.kts` too to prevent downgrades.

2023-04-26 13:19 UTC, arkon commented on data/src/main/sqldelight/tachiyomi/data/mangas.sq
> +    calculate_interval INTEGER DEFAULT 0 NOT NULL ,
```suggestion
    calculate_interval INTEGER DEFAULT 0 NOT NULL,
```

2023-04-26 13:19 UTC, arkon commented on data/src/main/java/tachiyomi/data/manga/MangaMapper.kt
> +            calculateInterval = calculateInterval.toInt(),
I'm guessing the intention is that the interval will never be that big, but it's probably simpler to just leave it as a `Long`.

2023-04-26 19:42 UTC, quangkieu commented on data/src/main/java/tachiyomi/data/manga/MangaMapper.kt
> +            calculateInterval = calculateInterval.toInt(),
Yes, I did not want to change column type so I just use Long for Inverval

2023-04-26 19:43 UTC, quangkieu commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupManager.kt
> +                calculateInterval = 0L,
Updated

2023-04-26 19:43 UTC, quangkieu commented on data/src/main/sqldelight/tachiyomi/migrations/24.sqm
> +ALTER TABLE mangas ADD COLUMN calculate_interval INTEGER DEFAULT 0 NOT NULL;
Updated

2023-04-26 19:43 UTC, quangkieu commented on data/src/main/sqldelight/tachiyomi/data/mangas.sq
> +    calculate_interval INTEGER DEFAULT 0 NOT NULL ,
Updated

2023-04-26 19:47 UTC, quangkieu commented
> Make sure to bump up the `versionCode` in `app/build.gradle.kts` too to prevent downgrades.

I would bump before the whole feature merge

2023-04-26 19:49 UTC, arkon commented
We can do multiple version bumps as things get merged. Attempting to downgrade the database if you install an older version leads to more headaches than it's worth.

2023-04-27 01:22 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/manga/model/Manga.kt
> +    val calculateInterval: Int,
Tell me if I'm wrong but I think @arkon meant to change this to Long

2023-04-27 06:17 UTC, quangkieu commented on domain/src/main/java/tachiyomi/domain/manga/model/Manga.kt
> +    val calculateInterval: Int,
Sure I could convert to Long but I see it would hit the front ui more to convert to Int for pluralStringResource and some calculations now use Long operation instead of Int.
Right now only the read/write to db need 1 time covert to Int

2023-04-28 02:27 UTC, merged

2023-04-28 04:12 UTC, quangkieu commented
Thanks arkon