Trackers empty scores start starts from middle
tachiyomiorg/tachiyomi pull request #9624
Opened 2023-06-22 15:30 UTC by semenvav

close #9412

When the score of an added tracker has yet to be specified, the initial value was 0, and now the middle of the scale.
I think this is a good idea, because most of the ratings are > 5/50 and this will greatly reduce the time to scroll, if the tracker allows you to put ratings from 1 to 100

2023-06-22 18:01 UTC, ivaniskandar commented
This will also affect non-empty score selection

2023-06-22 21:08 UTC, semenvav commented
Yes, that was very stupid of me. Hope everything is ok now

2023-06-23 02:11 UTC, arkon requested changes

2023-06-23 02:11 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/track/TrackInfoDialogSelector.kt
> +                startIndex = if (selections.indexOf(selection) > 0) selections.indexOf(selection) else (selections.size / 2),
Could probably do something like

```suggestion
                startIndex = selections.indexOf(selection).takeIf { it >= 0 } ?: selections.size / 2,
```

(Notably you need `>=`)

2023-06-23 12:59 UTC, semenvav commented on app/src/main/java/eu/kanade/presentation/track/TrackInfoDialogSelector.kt
> +                startIndex = if (selections.indexOf(selection) > 0) selections.indexOf(selection) else (selections.size / 2),
Are you sure I need to use >=. In this case? It will only work for Anilist with the Smiley system. In the bind method, if remoteTrack = zero, score = 0F is written. Everywhere except Anilist with the Smiley system 0 is included in the ScoreList and accordingly selections.indexOf(selection) will return 0 if no score is set. Also 0 in all these systems is not an score and means no score.

2023-06-23 21:53 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/track/TrackInfoDialogSelector.kt
> +                startIndex = if (selections.indexOf(selection) > 0) selections.indexOf(selection) else (selections.size / 2),
That's a good call, but the fact that it won't handle the smiley system is also a problem.

2023-06-23 22:17 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/track/TrackInfoDialogSelector.kt
> +                startIndex = if (selections.indexOf(selection) > 0) selections.indexOf(selection) else (selections.size / 2),
Sure. Can you just update it with the takeIf then?

2023-06-23 22:21 UTC, semenvav commented on app/src/main/java/eu/kanade/presentation/track/TrackInfoDialogSelector.kt
> +                startIndex = if (selections.indexOf(selection) > 0) selections.indexOf(selection) else (selections.size / 2),
Of course, as soon as I get to the computer

2023-06-24 14:37 UTC, merged