Add Tachiyomi Cross Device Sync Feature
tachiyomiorg/tachiyomi pull request #9675
Opened 2023-07-06 10:41 UTC by AriaMoradi

Continuing work from #9326

There will be subsequent PRs adding more features to sync.

2023-07-06 13:02 UTC, AntsyLich requested changes
Extra opnions:
- The backup related stuff that are now also being used by sync now should be renamed to something else to indicate it's used by both
- Imo we should implement google drive sync first since more people are likely to use that instead of a self hosted server. I personally won't be able to host syncyomi any time soon and won't be able to test either.

2023-07-06 16:37 UTC, AriaMoradi commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsSyncScreen.kt
> +    }
errors out saying remember delegate doesn't have a `setValue()`

2023-07-06 16:44 UTC, AriaMoradi commented
> Imo we should implement google drive sync first since more people are likely to use that instead of a self hosted server. I personally won't be able to host syncyomi any time soon and won't be able to test either.

Coming up in the next PR, if I add it back we'll get what was in the original PR

2023-07-06 16:48 UTC, jobobby04 commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsSyncScreen.kt
> +    }
You have to import setValue, `import androidx.compose.runtime.setValue`

2023-07-06 17:48 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/sync/SyncPreferences.kt
> +    fun syncService() = preferenceStore.getInt("sync_service", 0)
Use enum preference

2023-07-07 09:39 UTC, KaiserBh reviewed
Need to change some stuff right now it's broken when I last tested this (fixes in master branch), Also remember what we talked about, since right now we are getting the whole manga from database instead of favorites only it will be a lot of unnecessary data, and one of your suggestion was that we add lastFavoritedAt, so might as well implement that with this PR since it's part of the base.

2023-07-07 09:39 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncManager.kt
> +            SyncHolder.backup = backup.copy(backupManga = filteredFavorites)
This is wrong by the way, It won't restore the categories and just place all the manga in the default categories instead.

I have updated it in the master branch and fixed it @AriaMoradi but basically we want to copy the rest of the data as well.

```suggestion
            SyncHolder.backup = backup.copy(
                backupManga = filteredFavorites,
                backupCategories = remoteBackup.backupCategories,
                backupSources = remoteBackup.backupSources,
                backupBrokenSources = remoteBackup.backupBrokenSources,
            )
```

2023-07-07 09:39 UTC, KaiserBh commented on domain/src/main/java/tachiyomi/domain/sync/SyncPreferences.kt
> +    fun deviceID() = preferenceStore.getInt("device_id", 0)
Can remove this now I am not using it in syncyomi server anymore.
```suggestion
```

2023-07-07 09:39 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/service/SyncYomiSyncService.kt
This whole file is changed and the api endpoint changed as well check master branch for the latest one, might need to refactor the merging function at the moment I just dump it there but maybe another class that manage them maybe? Since it will be used by all services? Such as GoogleDrive, SyncYomi, WebDav, and any other cloud services maybe. 

@AriaMoradi

2023-07-07 13:39 UTC, arkon commented
If you're going to split into smaller PRs, do the database-related changes in 1 PR (and _only_ those changes, including an app version increase).

2023-07-07 19:58 UTC, AriaMoradi commented
Merged backup and sync settings screens

![image](https://github.com/tachiyomiorg/tachiyomi/assets/8719233/f5d6913e-c3c1-4d1b-a53c-cff7b1457b2c)
![image](https://github.com/tachiyomiorg/tachiyomi/assets/8719233/d87f3bca-d271-44a8-9b47-afdd2a09fcbd)
![image](https://github.com/tachiyomiorg/tachiyomi/assets/8719233/f393d938-0eac-4aef-ac2b-e0a9e1f7e4e3)

2023-07-08 12:19 UTC, KaiserBh commented
> If you're going to split into smaller PRs, do the database-related changes in 1 PR (and _only_ those changes, including an app version increase).

#9683 opened the PR.

2023-07-08 12:25 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/service/SyncService.kt
> +    abstract suspend fun pullSyncData(syncData: SyncData)
I think you mixed the comments for the two @AriaMoradi

2023-07-08 12:26 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/service/SyncYomiSyncService.kt
> +    override suspend fun pullSyncData(syncData: SyncData) {
This too should it be pull for uploading/updating the data? @AriaMoradi

2023-07-10 20:46 UTC, arkon commented
Next PR should ideally just be any changes to the existing backup/restore stuff.

2023-07-11 09:26 UTC, KaiserBh commented
> Next PR should ideally just be any changes to the existing backup/restore stuff.

#9699

2023-07-16 10:38 UTC, KaiserBh commented
This PR should be ready once #9699 is merged.

2023-07-24 05:27 UTC, quangkieu commented
My question would be for the conflict comic? So Machine 1 sync comic A read to chapter 10 but Machine 2 said comic A is at chapter 20? or chapter the fetch time, chapter update time, I know this one would change as some source just said New without date for like 2 day before put a update date, or the cover image as user could customize?

2023-07-24 05:50 UTC, KaiserBh commented
> My question would be for the conflict comic? So Machine 1 sync comic A read to chapter 10 but Machine 2 said comic A is at chapter 20? or chapter the fetch time, chapter update time, I know this one would change as some source just said New without date for like 2 day before put a update date, or the cover image as user could customize? If we have a dialog to show the conflict and last edit day per manga/comic would be greater to resolve that I think the last edit of each comic would be good to identify which version to keep. But what about when user restore from a backup, the edit time would be always newer from the sync copy. I would suggest to disable sync when restoring from backup and have feature to force update or restore from the cloud snapshot

Hi, I believe we have addressed the issue with conflicts you can read more on the last PR from [here](https://github.com/tachiyomiorg/tachiyomi/pull/9326#discussion_r1167644619) when arkon first mentioned it, and [this](https://github.com/tachiyomiorg/tachiyomi/pull/9326#issuecomment-1516704933)

2023-11-18 06:08 UTC, Riztard commented
included in #9790

2023-11-18 06:08 UTC, closed without merging