Add Tachiyomi Cross Device Sync Feature [Data Layer]
tachiyomiorg/tachiyomi pull request #9683
Opened 2023-07-08 12:19 UTC by KaiserBh

Database Changes only as requested.

I believe this will be all that's needed in terms of database changes, let me know if there is anything I need to change.

2023-07-08 14:01 UTC, arkon commented on data/src/main/sqldelight/tachiyomi/migrations/25.sqm
> +-- Rename existing tables to temporary tables
Can't you just add columns to the existing tables? Why the effectively complete replacements?

2023-07-08 18:59 UTC, AriaMoradi commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupChapter.kt
> +    @ProtoNumber(12) var lastFavoritedAt: Long? = null,
We decided to name the field `favoriteModifiedAt`, why change it to `lastFavoritedAt`?

2023-07-09 02:38 UTC, KaiserBh commented on data/src/main/sqldelight/tachiyomi/migrations/25.sqm
> +-- Rename existing tables to temporary tables
Not sure why I did it that way but fixed it.

2023-07-09 02:45 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupChapter.kt
> +    @ProtoNumber(12) var lastFavoritedAt: Long? = null,
does it matter? I just made it the same for consistency.

2023-07-09 03:09 UTC, AriaMoradi commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupChapter.kt
> +    @ProtoNumber(12) var lastFavoritedAt: Long? = null,
the meaning is very different

2023-07-09 07:05 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/manga/model/Manga.kt
> +    val lastFavoritedAt: Long?,
Looking at #9675 this isn't actually being shown anywhere on the ui so any need to add it to `Manga` object?

2023-07-09 09:53 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupManga.kt
> +    @ProtoNumber(107) var lastFavoritedAt: Long? = 0,
> If this field stores when a title was added to/removed from library it should be `favoriteModifiedAt`

It only accounts for adding to favorite not removing, I will change it to `favoriteModifiedAt`.

2023-07-09 10:08 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupManga.kt
> +    @ProtoNumber(107) var lastFavoritedAt: Long? = 0,
Why not removing? If I remove the title from one device it should be removed from another too

2023-07-09 10:12 UTC, AriaMoradi commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupChapter.kt
> +    @ProtoNumber(12) var lastFavoritedAt: Long? = null,
There is no concept of favoriting chapters but there is a bookmark feature and reading status.

2023-07-09 10:13 UTC, AriaMoradi commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupManga.kt
> +    @ProtoNumber(107) var lastFavoritedAt: Long? = 0,
> It only accounts for adding to favorite not removing

Correction: default value is null, value is set when user toggles favorite so both adding and removing.

2023-07-09 10:15 UTC, AriaMoradi commented on domain/src/main/java/tachiyomi/domain/manga/model/Manga.kt
> +    val lastFavoritedAt: Long?,
every manga has these fields associated with it, the alternative is adding a one to one foreign key which won't be useful much as it is needed most of the time imo.

2023-07-09 10:18 UTC, AriaMoradi commented on app/build.gradle.kts
> +
arkon asked to bump app version, are we doing it incorrectly?

2023-07-09 10:40 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupManga.kt
> +    @ProtoNumber(107) var lastFavoritedAt: Long? = 0,
> > It only accounts for adding to favorite not removing
> 
> Correction: default value is null, value is set when user toggles favorite so both adding and removing.

Oh yea that's true, I thought it was just accounting for adding and not removing. Thanks for the correction.

2023-07-09 10:57 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupChapter.kt
> +    @ProtoNumber(12) var lastFavoritedAt: Long? = null,
Yea that's not meant to be there. Fixed in the latest commit.

2023-07-09 11:23 UTC, AntsyLich commented on app/build.gradle.kts
> +
No the version bump is ok but you were also reverting a change from another commit in the process. It's fixed now

2023-07-09 11:23 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/manga/model/Manga.kt
> +    val lastFavoritedAt: Long?,
I mean it's fine to keep it in db but is it needed to be in the manga object too?

2023-07-09 11:52 UTC, KaiserBh commented on domain/src/main/java/tachiyomi/domain/manga/model/Manga.kt
> +    val lastFavoritedAt: Long?,
> I mean it's fine to keep it in db but is it needed to be in the manga object too?

If we store these values in the DB without exposing them in the manga object, they essentially become redundant. The BackupManga class copies data from the Manga object, and these fields play an essential role in our internal merging and syncing logic. You can refer to the implementation [here](https://github.com/tachiyomiorg/tachiyomi/pull/9675/files#diff-c058878952993eb2cd615c786376f0c38efc6e1af2663c41ceaa425a40362558R61-R231)

2023-07-09 13:58 UTC, arkon commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupManga.kt
> +    @ProtoNumber(107) var favoriteModifiedAt: Long? = 0,
I imagine looking at part of the larger PR might answer this, but why do we need both of these timestamps?

2023-07-09 13:58 UTC, arkon commented on data/src/main/sqldelight/tachiyomi/migrations/25.sqm
> +ALTER TABLE chapters ADD COLUMN last_modified_at INTEGER AS Long;
Should we attempt to backfill these values?

2023-07-10 11:56 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupManga.kt
> +    @ProtoNumber(107) var favoriteModifiedAt: Long? = 0,
> I imagine looking at part of the larger PR might answer this, but why do we need both of these timestamps?

There was an issue when syncing manga favorites between devices, primarily when a manga was removed from favorites (Library). Initially, our sync system only tracked favorited manga. Here's how that led to issues:

Let's say we have two devices, Device A and Device B. Now, imagine a user removes a manga – let's use "One Piece" as an example – from their favorites on Device A and then syncs the device. The problem arose when Device B, which already had "One Piece" in its favorites, tried to sync. Instead of deleting "One Piece" from its favorites to mirror the change made on Device A, Device B would end up restoring "One Piece" back into the favorites. The unintended consequence was that if we synced Device A again, "One Piece" would incorrectly be restored to its favorites, even though the user had initially removed it.

To address this issue, I decided to keep a record of every manga on the device, not just the ones marked as favorites. This approach also includes manga that users might have searched for but didn't add to their library. However,  Aria mentioned that some users have thousands data in their phone that are not in favorite etc, therefore it will be a lot of unnecessary data being sent to server/services increase data usage etc.

In order to tackle this, @AriaMoradi proposed incorporating a favoriteModifiedAt timestamp. With this timestamp, we still have non-favorite manga data, but it is not as extensive as it would have been without the timestamp. We can now sync manga where favoriteModifiedAt != null, which effectively reduces the amount of irrelevant data that are being synced.

2023-07-10 12:03 UTC, KaiserBh commented on data/src/main/sqldelight/tachiyomi/migrations/25.sqm
> +ALTER TABLE chapters ADD COLUMN last_modified_at INTEGER AS Long;
Oh yea we definitely should do that.

Will something like this do?

```sql UPDATE mangas SET last_modified_at = strftime('%s', 'now');
UPDATE mangas_categories SET last_modified_at = strftime('%s', 'now');
UPDATE chapters SET last_modified_at = strftime('%s', 'now');
UPDATE mangas SET favorite_modified_at = strftime('%s', 'now') WHERE favorite = 1;
```

2023-07-10 12:29 UTC, AntsyLich commented on data/src/main/sqldelight/tachiyomi/migrations/25.sqm
> +ALTER TABLE chapters ADD COLUMN last_modified_at INTEGER AS Long;
You missed `mangas` `last_modified_at`. Also might as well `last_modified_at` for all of them non-null

2023-07-10 14:06 UTC, AntsyLich requested changes

2023-07-10 14:06 UTC, AntsyLich commented on data/src/main/sqldelight/tachiyomi/data/mangas.sq
> +END;
Redundant?

2023-07-10 14:06 UTC, AntsyLich commented on data/src/main/sqldelight/tachiyomi/data/mangas_categories.sq
> +END;
This too

2023-07-10 14:06 UTC, AntsyLich commented on data/src/main/sqldelight/tachiyomi/migrations/25.sqm
> +END;
3

2023-07-10 14:06 UTC, AntsyLich commented on data/src/main/sqldelight/tachiyomi/migrations/25.sqm
> +END;
4

2023-07-10 16:16 UTC, AntsyLich requested changes

2023-07-10 16:16 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/chapter/model/Chapter.kt
> +    val lastModifiedAt: Long?,
```suggestion
    val lastModifiedAt: Long,
```

2023-07-10 16:16 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/chapter/model/Chapter.kt
> +            lastModifiedAt = null,
```suggestion
            lastModifiedAt = 0,
```

2023-07-10 16:16 UTC, AntsyLich commented on domain/src/main/java/tachiyomi/domain/manga/model/Manga.kt
> +    val lastModifiedAt: Long?,
```suggestion
    val lastModifiedAt: Long,
```

2023-07-10 19:42 UTC, arkon approved these changes

2023-07-10 19:52 UTC, merged