Refactor backup and restore to support cross device sync.
tachiyomiorg/tachiyomi pull request #9699
Opened 2023-07-11 09:25 UTC by KaiserBh

Backup and restore refactor.

2023-07-11 09:54 UTC, AntsyLich requested changes

2023-07-11 09:54 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncHolder.kt
> +    var backup: Backup? = null
What is the purpose of `SyncHolder`? I can see that it's being used in other files but why is it needed

2023-07-11 09:59 UTC, THElegend5 commented
Btw does this also result a change in tachiyomi backup modals?

2023-07-11 10:21 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncHolder.kt
> +    var backup: Backup? = null
I don't quite remember but from this [commit](https://github.com/tachiyomiorg/tachiyomi/commit/0a1137414efa05fc87e2669ed654bcda71c37ad9) if am not wrong I added it because I couldn't use the object directly in the worker or something I tried to convert the json into backup object but getting error that there is limit in worker etc. So I made sync holder which just holds the current value/data we get from the server that have been turned into object from json. Then again I think it can be refactored, once the last bit of the PR is added.

2023-07-11 10:31 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncHolder.kt
> +    var backup: Backup? = null
Imo it would be better to save the `Backup` object as protobuf inside application data folder. This way we can just directly pass the uri to restore functions

2023-07-11 10:46 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncHolder.kt
> +    var backup: Backup? = null
Yea that would probably be better and we can eliminate the boolean that is being used @AriaMoradi mentioned something similar that we should refactor it and not use the boolean/syncHolder. Can refactor it once everything is together as it will be easier to test and see if it's working as intended.

2023-07-11 10:56 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncHolder.kt
> +    var backup: Backup? = null
Imo we should make the changes now and test them slowly rather than when the changes are more big

2023-07-11 11:08 UTC, KaiserBh commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncHolder.kt
> +    var backup: Backup? = null
> Imo we should make the changes now and test them slowly rather than when the changes are more big

Next PR will be this #9675 I will refactor it there then before we open the one after that which will be Gdrive implementation which is the biggest one.

2023-07-11 11:15 UTC, AntsyLich commented on app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncHolder.kt
> +    var backup: Backup? = null
OK then the restore functions could be renamed to sync (e.g. `restoreBackup` -> `syncFromBackup`) since at the end they are syncing (backup file being a local source) and similarly to backup functions (e.g. `backupExtensionInfo` -> `prepExtensionInfoForSync`)

2023-07-14 16:08 UTC, AntsyLich commented
@arkon can we just replace the backup terminology to sync in the code?

2023-07-14 16:23 UTC, arkon commented
I think I'd still consider it a backup restore, but syncing could be considered an overwrite mode instead of an append mode.

2023-07-22 22:39 UTC, arkon commented on i18n/src/main/res/values/strings.xml
> +    <string name="library_sync_complete">Library sync complete</string>
I actually feel like this doesn't need to be a notification, but we can maybe mull about that in the final PR.

2023-07-22 22:39 UTC, merged