Add support to kotlin.time APIs in the rate limit interceptor
tachiyomiorg/tachiyomi pull request #9797
Opened 2023-08-03 19:48 UTC by alessandrojean

I kept the old legacy method to maintain compatibility with the existing codebase for the extensions, but under the hoods it is already using the `kotlin.time` APIs by converting the types.

The existing code can be migrated after some time and the legacy method marked as obsolete.

This will allow the usage of the methods like so:

```kotlin
client.newBuilder()
    .rateLimit(1, 2.seconds)
    .rateLimitHost(baseUrl.toHttpUrl(), 1, 3.seconds)
    .build()
```

2023-08-03 19:53 UTC, AntsyLich commented
Imo should put the new `rateLimitHost` inside `RateLimitInterceptor.kt` so we can remove the `SpecificHostRateLimitInterceptor.kt` file later

2023-08-03 19:53 UTC, AntsyLich commented
Also don't forget a pr against https://github.com/tachiyomiorg/extensions-lib

2023-08-03 21:26 UTC, arkon requested changes
Mark the old ones as deprecated too, and we can just outright remove them from extension-lib 1.5 and update everything at once so we can drop them from the codebase soon thereafter.

2023-08-03 21:26 UTC, arkon commented on core/src/main/java/eu/kanade/tachiyomi/network/interceptor/SpecificHostRateLimitInterceptor.kt
> -fun OkHttpClient.Builder.rateLimitHost(
I think this actually needs to stay in this file for the stuff to match up.

2023-08-04 08:33 UTC, AntsyLich commented on core/src/main/java/eu/kanade/tachiyomi/network/interceptor/SpecificHostRateLimitInterceptor.kt
> -fun OkHttpClient.Builder.rateLimitHost(
Yeah the old one needs to be kept in this file otherwise extensions will break. @stevenyomi tested this during the intercept rewrite.

2023-08-04 21:11 UTC, merged