Added more common exceptions
tachiyomiorg/tachiyomi pull request #9883
Opened 2023-08-27 11:22 UTC by Programmer-0-0

Added more common exceptions that will be used in #9795

2023-08-27 18:41 UTC, alessandrojean requested changes

2023-08-27 18:41 UTC, alessandrojean commented on app/src/main/java/eu/kanade/presentation/util/ExceptionFormatter.kt
> +            "IOException" -> if (isOnline()) getString(R.string.exception_io_error) else getString(R.string.exception_offline)
IOException is used inside the extensions interceptors to throw custom errors, so needs to be kept with the Exception guard as it was before.

2023-08-27 18:44 UTC, alessandrojean commented on app/src/main/java/eu/kanade/presentation/util/ExceptionFormatter.kt
> +            "IllegalStateException" -> getString(R.string.exception_unexpected_state)
Some extensions also throws this with custom error messages while using `checkNotNull`, so needs to be removed as well.

2023-08-27 18:45 UTC, alessandrojean commented
I think a good start would be addressing the fetching errors first, which are thrown by OkHttp and can't be manually thrown from inside the extensions.

2023-08-28 04:38 UTC, stevenyomi commented
I think most of these strings are useless. Most of the exceptions are rarely seen, and explaining them doesn't enable users to troubleshoot and solve the issue themselves.

2023-10-18 16:16 UTC, closed without merging