Changed login method of bangumi tracker
tachiyomiorg/tachiyomi pull request #9941
Opened 2023-09-17 14:56 UTC by KayZhang52

Changed the bangumi tracker's authentication to a dialog. User will have to go to the new token site, generate the token and add it here with the expiry date. Does solve the 7 day problem though.
  
  If your changes are visual, please provide images below:

![screenshot](https://github.com/tachiyomiorg/tachiyomi/assets/46264322/14aeca10-7b3d-456d-bc2f-5a00e6ae292a)

2023-09-17 15:36 UTC, alessandrojean requested changes

2023-09-17 15:36 UTC, alessandrojean commented on app/build.gradle.kts
> +        applicationId = "eu.kanade.tachiyomi_bangumi_tracker_expiry"
This shouldn't be commited.

2023-09-17 15:36 UTC, alessandrojean commented on app/src/main/AndroidManifest.xml
> +        android:label="Tachiyomi_track_bangumi_fix"
Neither this.

2023-09-17 19:17 UTC, mutsumi63 commented
> Changed the bangumi tracker's authentication to a dialog. User will have to go to the new token site, generate the token and add it here with the expiry date. Does solve the 7 day problem though.
> 
> ![screenshot](https://user-images.githubusercontent.com/46264322/268510075-14aeca10-7b3d-456d-bc2f-5a00e6ae292a.jpg)

In the dialog box, there may be a need for some explanations and URL link.

2023-09-18 16:03 UTC, KayZhang52 commented on app/src/main/AndroidManifest.xml
> +        android:label="Tachiyomi_track_bangumi_fix"
> Neither this.

Removed. My bad.

2023-09-18 18:18 UTC, mutsumi63 commented
![image](https://github.com/tachiyomiorg/tachiyomi/assets/4182301/b08be337-b8bd-4aca-9b95-e6cb3c6838ca)

![image](https://github.com/tachiyomiorg/tachiyomi/assets/4182301/4ea8e853-dd97-4bed-9b94-d07eb50983ba)

Click the tracker again will reset the local records to empty/0.

Click rating button causes a crash.

2023-10-07 02:56 UTC, arkon requested changes
Seems like @mutsumi63 pointed out some functional issues too?

2023-10-07 02:56 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
> +                        text = "Enter access token for Bangumi",
Any text in the UI should be added to `strings.xml` instead.

2023-10-07 02:56 UTC, arkon commented on app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
> +                    OutlinedTextField(
Why does the user need to specify this?

2023-10-07 02:56 UTC, arkon commented on gradle/kotlinx.versions.toml
> +xml_serialization_version = "0.86.1"
These dependency downgrades should be removed.

2023-10-07 11:12 UTC, mutsumi63 commented
> Seems like @mutsumi63 pointed out some functional issues too?

I added some details.

2024-01-07 22:40 UTC, closed without merging

2024-01-07 22:40 UTC, arkon commented
Assuming this is abandoned.